// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const authorizeSMSCharge = `-- name: AuthorizeSMSCharge :one
WITH billing_account AS MATERIALIZED (
    SELECT
        team.id AS team_id,
        team.market_code,
        wallet.currency,
        wallet.tier,
        wallet.balance_units,
        CASE
            WHEN team.market_code = $2 THEN 'sms_local'
            ELSE 'sms_intl'
        END AS product
    FROM teams AS team
    JOIN team_wallets AS wallet ON wallet.team_id = team.id
    WHERE team.id = $3
      AND team.status = 'active'
      AND team.market_code IN ('GH', 'KE')
    FOR UPDATE OF wallet
),
resolved_rate AS MATERIALIZED (
    SELECT
        account.team_id, account.market_code, account.currency, account.tier, account.balance_units, account.product,
        rate.cost_units,
        rate.currency AS rate_currency,
        rate.cost_units * $1::bigint AS amount_units
    FROM billing_account AS account
    JOIN product_rates AS rate
      ON rate.market_code = account.market_code
     AND rate.product = account.product
     AND rate.tier = account.tier
     AND rate.is_active = true
),
existing_ledger AS MATERIALIZED (
    SELECT ledger.id
    FROM wallet_ledger AS ledger
    JOIN billing_account AS account ON account.team_id = ledger.team_id
    WHERE ledger.transaction_type = 'usage_sms'
      AND ledger.reference_id = $4
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        rate.team_id,
        -rate.amount_units,
        'usage_sms',
        $4
    FROM resolved_rate AS rate
    WHERE rate.currency = rate.rate_currency
      AND rate.currency = CASE rate.market_code
          WHEN 'GH' THEN 'GHS'
          WHEN 'KE' THEN 'KES'
      END
      AND rate.balance_units >= rate.amount_units
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.balance_units
)
SELECT
    CASE
        WHEN NOT EXISTS (SELECT 1 FROM billing_account) THEN 'account_not_found'
        WHEN NOT EXISTS (SELECT 1 FROM resolved_rate) THEN 'rate_not_found'
        WHEN EXISTS (
            SELECT 1
            FROM resolved_rate
            WHERE currency <> rate_currency
               OR currency <> CASE market_code
                   WHEN 'GH' THEN 'GHS'
                   WHEN 'KE' THEN 'KES'
               END
        ) THEN 'currency_mismatch'
        WHEN EXISTS (SELECT 1 FROM existing_ledger) THEN 'already_applied'
        WHEN EXISTS (SELECT 1 FROM updated_wallet) THEN 'applied'
        WHEN EXISTS (
            SELECT 1 FROM resolved_rate
            WHERE balance_units < amount_units
        ) THEN 'insufficient_balance'
        ELSE 'already_applied'
    END AS outcome,
    COALESCE((SELECT market_code FROM resolved_rate), '')::text AS market_code,
    COALESCE((SELECT currency FROM resolved_rate), '')::text AS currency,
    COALESCE((SELECT tier FROM resolved_rate), '')::text AS tier,
    COALESCE((SELECT product FROM resolved_rate), '')::text AS product,
    COALESCE((SELECT cost_units FROM resolved_rate), 0)::bigint AS unit_cost_units,
    $1::bigint AS quantity,
    COALESCE((SELECT amount_units FROM resolved_rate), 0)::bigint AS amount_units,
    COALESCE(
        (SELECT balance_units FROM updated_wallet),
        (SELECT balance_units FROM resolved_rate),
        0
    )::bigint AS balance_units
`

type AuthorizeSMSChargeParams struct {
	Segments           int64     `db:"segments" json:"segments"`
	DestinationCountry string    `db:"destination_country" json:"destination_country"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
	ReferenceID        string    `db:"reference_id" json:"reference_id"`
}

type AuthorizeSMSChargeRow struct {
	Outcome       string `db:"outcome" json:"outcome"`
	MarketCode    string `db:"market_code" json:"market_code"`
	Currency      string `db:"currency" json:"currency"`
	Tier          string `db:"tier" json:"tier"`
	Product       string `db:"product" json:"product"`
	UnitCostUnits int64  `db:"unit_cost_units" json:"unit_cost_units"`
	Quantity      int64  `db:"quantity" json:"quantity"`
	AmountUnits   int64  `db:"amount_units" json:"amount_units"`
	BalanceUnits  int64  `db:"balance_units" json:"balance_units"`
}

func (q *Queries) AuthorizeSMSCharge(ctx context.Context, arg AuthorizeSMSChargeParams) (AuthorizeSMSChargeRow, error) {
	row := q.db.QueryRow(ctx, authorizeSMSCharge,
		arg.Segments,
		arg.DestinationCountry,
		arg.TeamID,
		arg.ReferenceID,
	)
	var i AuthorizeSMSChargeRow
	err := row.Scan(
		&i.Outcome,
		&i.MarketCode,
		&i.Currency,
		&i.Tier,
		&i.Product,
		&i.UnitCostUnits,
		&i.Quantity,
		&i.AmountUnits,
		&i.BalanceUnits,
	)
	return i, err
}

const consumeFreeEmailAllowance = `-- name: ConsumeFreeEmailAllowance :one
UPDATE team_wallets
SET free_email_allowance = free_email_allowance - 1,
    updated_at = now()
WHERE team_id = $1
  AND free_email_allowance > 0
RETURNING team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
`

type ConsumeFreeEmailAllowanceParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ConsumeFreeEmailAllowance(ctx context.Context, arg ConsumeFreeEmailAllowanceParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, consumeFreeEmailAllowance, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const creditTeamWallet = `-- name: CreditTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.currency, wallet.balance_units, wallet.tier, wallet.free_email_allowance, wallet.last_allowance_reset, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        $2,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.currency, wallet.balance_units, wallet.tier, wallet.free_email_allowance, wallet.last_allowance_reset, wallet.created_at, wallet.updated_at
)
SELECT team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
FROM updated_wallet
`

type CreditTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type CreditTeamWalletRow struct {
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	Currency           string             `db:"currency" json:"currency"`
	BalanceUnits       int64              `db:"balance_units" json:"balance_units"`
	Tier               string             `db:"tier" json:"tier"`
	FreeEmailAllowance int32              `db:"free_email_allowance" json:"free_email_allowance"`
	LastAllowanceReset pgtype.Timestamptz `db:"last_allowance_reset" json:"last_allowance_reset"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreditTeamWallet(ctx context.Context, arg CreditTeamWalletParams) (CreditTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, creditTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i CreditTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitTeamWallet = `-- name: DebitTeamWallet :one
WITH locked_wallet AS MATERIALIZED (
    SELECT wallet.team_id, wallet.currency, wallet.balance_units, wallet.tier, wallet.free_email_allowance, wallet.last_allowance_reset, wallet.created_at, wallet.updated_at
    FROM team_wallets AS wallet
    WHERE wallet.team_id = $1
    FOR UPDATE
),
inserted_ledger AS (
    INSERT INTO wallet_ledger (
        team_id,
        amount_units,
        transaction_type,
        reference_id
    )
    SELECT
        wallet.team_id,
        -$2::bigint,
        $3,
        $4
    FROM locked_wallet AS wallet
    WHERE $2::bigint > 0
      AND wallet.balance_units >= $2
    ON CONFLICT (team_id, transaction_type, reference_id) DO NOTHING
    RETURNING team_id, amount_units
),
updated_wallet AS (
    UPDATE team_wallets AS wallet
    SET balance_units = wallet.balance_units + ledger.amount_units,
        updated_at = now()
    FROM inserted_ledger AS ledger
    WHERE wallet.team_id = ledger.team_id
    RETURNING wallet.team_id, wallet.currency, wallet.balance_units, wallet.tier, wallet.free_email_allowance, wallet.last_allowance_reset, wallet.created_at, wallet.updated_at
)
SELECT team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
FROM updated_wallet
`

type DebitTeamWalletParams struct {
	TeamID          uuid.UUID `db:"team_id" json:"team_id"`
	AmountUnits     int64     `db:"amount_units" json:"amount_units"`
	TransactionType string    `db:"transaction_type" json:"transaction_type"`
	ReferenceID     string    `db:"reference_id" json:"reference_id"`
}

type DebitTeamWalletRow struct {
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	Currency           string             `db:"currency" json:"currency"`
	BalanceUnits       int64              `db:"balance_units" json:"balance_units"`
	Tier               string             `db:"tier" json:"tier"`
	FreeEmailAllowance int32              `db:"free_email_allowance" json:"free_email_allowance"`
	LastAllowanceReset pgtype.Timestamptz `db:"last_allowance_reset" json:"last_allowance_reset"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DebitTeamWallet(ctx context.Context, arg DebitTeamWalletParams) (DebitTeamWalletRow, error) {
	row := q.db.QueryRow(ctx, debitTeamWallet,
		arg.TeamID,
		arg.AmountUnits,
		arg.TransactionType,
		arg.ReferenceID,
	)
	var i DebitTeamWalletRow
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProductRate = `-- name: GetActiveProductRate :one
SELECT id, product, market_code, tier, currency, cost_units, is_active, created_at, updated_at
FROM product_rates
WHERE market_code = $1
  AND product = $2
  AND tier = $3
  AND is_active = true
`

type GetActiveProductRateParams struct {
	MarketCode string `db:"market_code" json:"market_code"`
	Product    string `db:"product" json:"product"`
	Tier       string `db:"tier" json:"tier"`
}

func (q *Queries) GetActiveProductRate(ctx context.Context, arg GetActiveProductRateParams) (ProductRate, error) {
	row := q.db.QueryRow(ctx, getActiveProductRate, arg.MarketCode, arg.Product, arg.Tier)
	var i ProductRate
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.MarketCode,
		&i.Tier,
		&i.Currency,
		&i.CostUnits,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamWallet = `-- name: GetTeamWallet :one
SELECT team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
FROM team_wallets
WHERE team_id = $1
`

type GetTeamWalletParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetTeamWallet(ctx context.Context, arg GetTeamWalletParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, getTeamWallet, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletLedger = `-- name: ListWalletLedger :many
SELECT id, team_id, amount_units, transaction_type, reference_id, created_at
FROM wallet_ledger
WHERE team_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListWalletLedgerParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWalletLedger(ctx context.Context, arg ListWalletLedgerParams) ([]WalletLedger, error) {
	rows, err := q.db.Query(ctx, listWalletLedger, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletLedger{}
	for rows.Next() {
		var i WalletLedger
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.AmountUnits,
			&i.TransactionType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFreeEmailAllowance = `-- name: ResetFreeEmailAllowance :one
UPDATE team_wallets
SET free_email_allowance = $1,
    last_allowance_reset = now(),
    updated_at = now()
WHERE team_id = $2
  AND $1::integer >= 0
RETURNING team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
`

type ResetFreeEmailAllowanceParams struct {
	FreeEmailAllowance int32     `db:"free_email_allowance" json:"free_email_allowance"`
	TeamID             uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ResetFreeEmailAllowance(ctx context.Context, arg ResetFreeEmailAllowanceParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, resetFreeEmailAllowance, arg.FreeEmailAllowance, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamWalletTier = `-- name: UpdateTeamWalletTier :one
UPDATE team_wallets
SET tier = $1,
    updated_at = now()
WHERE team_id = $2
RETURNING team_id, currency, balance_units, tier, free_email_allowance, last_allowance_reset, created_at, updated_at
`

type UpdateTeamWalletTierParams struct {
	Tier   string    `db:"tier" json:"tier"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateTeamWalletTier(ctx context.Context, arg UpdateTeamWalletTierParams) (TeamWallet, error) {
	row := q.db.QueryRow(ctx, updateTeamWalletTier, arg.Tier, arg.TeamID)
	var i TeamWallet
	err := row.Scan(
		&i.TeamID,
		&i.Currency,
		&i.BalanceUnits,
		&i.Tier,
		&i.FreeEmailAllowance,
		&i.LastAllowanceReset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
