// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_provider_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailProviderEvent = `-- name: CreateEmailProviderEvent :execrows
INSERT INTO email_provider_events (
    id,
    email_message_id,
    provider,
    transport,
    provider_notification_id,
    provider_message_id,
    event_type,
    occurred_at,
    received_at,
    normalized_payload,
    provider_payload
) VALUES (
    $1,
    (
        SELECT id
        FROM email_messages
        WHERE provider = 'ses'
          AND provider_message_id = $2
    ),
    $3,
    $4,
    $5,
    $2,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (provider, transport, provider_notification_id) DO NOTHING
`

type CreateEmailProviderEventParams struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	ProviderMessageID      string             `db:"provider_message_id" json:"provider_message_id"`
	Provider               string             `db:"provider" json:"provider"`
	Transport              string             `db:"transport" json:"transport"`
	ProviderNotificationID string             `db:"provider_notification_id" json:"provider_notification_id"`
	EventType              string             `db:"event_type" json:"event_type"`
	OccurredAt             pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	ReceivedAt             pgtype.Timestamptz `db:"received_at" json:"received_at"`
	NormalizedPayload      []byte             `db:"normalized_payload" json:"normalized_payload"`
	ProviderPayload        []byte             `db:"provider_payload" json:"provider_payload"`
}

func (q *Queries) CreateEmailProviderEvent(ctx context.Context, arg CreateEmailProviderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEmailProviderEvent,
		arg.ID,
		arg.ProviderMessageID,
		arg.Provider,
		arg.Transport,
		arg.ProviderNotificationID,
		arg.EventType,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.NormalizedPayload,
		arg.ProviderPayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmailProviderEventByNotification = `-- name: GetEmailProviderEventByNotification :one
SELECT id, email_message_id, provider, transport, provider_notification_id, provider_message_id, event_type, occurred_at, received_at, normalized_payload, provider_payload, processed_at, created_at
FROM email_provider_events
WHERE provider = $1
  AND transport = $2
  AND provider_notification_id = $3
`

type GetEmailProviderEventByNotificationParams struct {
	Provider               string `db:"provider" json:"provider"`
	Transport              string `db:"transport" json:"transport"`
	ProviderNotificationID string `db:"provider_notification_id" json:"provider_notification_id"`
}

func (q *Queries) GetEmailProviderEventByNotification(ctx context.Context, arg GetEmailProviderEventByNotificationParams) (EmailProviderEvent, error) {
	row := q.db.QueryRow(ctx, getEmailProviderEventByNotification, arg.Provider, arg.Transport, arg.ProviderNotificationID)
	var i EmailProviderEvent
	err := row.Scan(
		&i.ID,
		&i.EmailMessageID,
		&i.Provider,
		&i.Transport,
		&i.ProviderNotificationID,
		&i.ProviderMessageID,
		&i.EventType,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.NormalizedPayload,
		&i.ProviderPayload,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const linkEmailProviderEvent = `-- name: LinkEmailProviderEvent :execrows
UPDATE email_provider_events AS event
SET email_message_id = message.id
FROM email_messages AS message
WHERE event.provider = $1
  AND event.transport = $2
  AND event.provider_notification_id = $3
  AND event.email_message_id IS NULL
  AND message.provider = 'ses'
  AND message.provider_message_id = event.provider_message_id
`

type LinkEmailProviderEventParams struct {
	Provider               string `db:"provider" json:"provider"`
	Transport              string `db:"transport" json:"transport"`
	ProviderNotificationID string `db:"provider_notification_id" json:"provider_notification_id"`
}

func (q *Queries) LinkEmailProviderEvent(ctx context.Context, arg LinkEmailProviderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkEmailProviderEvent, arg.Provider, arg.Transport, arg.ProviderNotificationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailProviderEventProcessed = `-- name: MarkEmailProviderEventProcessed :execrows
UPDATE email_provider_events
SET processed_at = COALESCE(processed_at, $1)
WHERE id = $2
`

type MarkEmailProviderEventProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) MarkEmailProviderEventProcessed(ctx context.Context, arg MarkEmailProviderEventProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markEmailProviderEventProcessed, arg.ProcessedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
