// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailMessage = `-- name: CreateEmailMessage :one
INSERT INTO email_messages (
    team_id,
    message_type,
    from_email,
    from_name,
    reply_to_email,
    to_email,
    to_name,
    subject,
    html_body,
    text_body,
    status,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'queued',
    $11
)
RETURNING id, team_id, message_type, from_email, from_name, reply_to_email, to_email, to_name, subject, html_body, text_body, status, provider, provider_message_id, error_code, error_message, metadata, queued_at, processing_at, submitted_at, delivered_at, failed_at, created_at, updated_at
`

type CreateEmailMessageParams struct {
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	MessageType  string    `db:"message_type" json:"message_type"`
	FromEmail    string    `db:"from_email" json:"from_email"`
	FromName     *string   `db:"from_name" json:"from_name"`
	ReplyToEmail *string   `db:"reply_to_email" json:"reply_to_email"`
	ToEmail      string    `db:"to_email" json:"to_email"`
	ToName       *string   `db:"to_name" json:"to_name"`
	Subject      string    `db:"subject" json:"subject"`
	HtmlBody     *string   `db:"html_body" json:"html_body"`
	TextBody     *string   `db:"text_body" json:"text_body"`
	Metadata     []byte    `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, createEmailMessage,
		arg.TeamID,
		arg.MessageType,
		arg.FromEmail,
		arg.FromName,
		arg.ReplyToEmail,
		arg.ToEmail,
		arg.ToName,
		arg.Subject,
		arg.HtmlBody,
		arg.TextBody,
		arg.Metadata,
	)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageType,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailMessage = `-- name: GetEmailMessage :one
SELECT id, team_id, message_type, from_email, from_name, reply_to_email, to_email, to_name, subject, html_body, text_body, status, provider, provider_message_id, error_code, error_message, metadata, queued_at, processing_at, submitted_at, delivered_at, failed_at, created_at, updated_at
FROM email_messages
WHERE id = $1
  AND team_id = $2
`

type GetEmailMessageParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetEmailMessage(ctx context.Context, arg GetEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, getEmailMessage, arg.ID, arg.TeamID)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageType,
		&i.FromEmail,
		&i.FromName,
		&i.ReplyToEmail,
		&i.ToEmail,
		&i.ToName,
		&i.Subject,
		&i.HtmlBody,
		&i.TextBody,
		&i.Status,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.QueuedAt,
		&i.ProcessingAt,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailMessages = `-- name: ListEmailMessages :many
SELECT
    id,
    team_id,
    to_email,
    to_name,
    subject,
    status,
    provider,
    queued_at,
    submitted_at,
    delivered_at,
    created_at
FROM email_messages
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListEmailMessagesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

type ListEmailMessagesRow struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	ToEmail     string             `db:"to_email" json:"to_email"`
	ToName      *string            `db:"to_name" json:"to_name"`
	Subject     string             `db:"subject" json:"subject"`
	Status      string             `db:"status" json:"status"`
	Provider    *string            `db:"provider" json:"provider"`
	QueuedAt    pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	SubmittedAt pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]ListEmailMessagesRow, error) {
	rows, err := q.db.Query(ctx, listEmailMessages, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailMessagesRow{}
	for rows.Next() {
		var i ListEmailMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ToEmail,
			&i.ToName,
			&i.Subject,
			&i.Status,
			&i.Provider,
			&i.QueuedAt,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
