// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_policies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTeamIdentityPolicy = `-- name: GetTeamIdentityPolicy :one
SELECT
    teams.id AS team_id,
    COALESCE(team_identity_policies.require_mfa, false)::boolean AS require_mfa,
    COALESCE(team_identity_policies.session_max_age_minutes, 43200)::integer AS session_max_age_minutes,
    team_identity_policies.updated_by,
    COALESCE(team_identity_policies.created_at, teams.created_at)::timestamptz AS created_at,
    COALESCE(team_identity_policies.updated_at, teams.created_at)::timestamptz AS updated_at
FROM teams
LEFT JOIN team_identity_policies ON team_identity_policies.team_id = teams.id
WHERE teams.id = $1
`

type GetTeamIdentityPolicyParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

type GetTeamIdentityPolicyRow struct {
	TeamID               uuid.UUID          `db:"team_id" json:"team_id"`
	RequireMfa           bool               `db:"require_mfa" json:"require_mfa"`
	SessionMaxAgeMinutes int32              `db:"session_max_age_minutes" json:"session_max_age_minutes"`
	UpdatedBy            *uuid.UUID         `db:"updated_by" json:"updated_by"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTeamIdentityPolicy(ctx context.Context, arg GetTeamIdentityPolicyParams) (GetTeamIdentityPolicyRow, error) {
	row := q.db.QueryRow(ctx, getTeamIdentityPolicy, arg.TeamID)
	var i GetTeamIdentityPolicyRow
	err := row.Scan(
		&i.TeamID,
		&i.RequireMfa,
		&i.SessionMaxAgeMinutes,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTeamIdentityPolicy = `-- name: UpsertTeamIdentityPolicy :one
INSERT INTO team_identity_policies (
    team_id,
    require_mfa,
    session_max_age_minutes,
    updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (team_id) DO UPDATE SET
    require_mfa = EXCLUDED.require_mfa,
    session_max_age_minutes = EXCLUDED.session_max_age_minutes,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING team_id, require_mfa, session_max_age_minutes, updated_by, created_at, updated_at
`

type UpsertTeamIdentityPolicyParams struct {
	TeamID               uuid.UUID  `db:"team_id" json:"team_id"`
	RequireMfa           bool       `db:"require_mfa" json:"require_mfa"`
	SessionMaxAgeMinutes int32      `db:"session_max_age_minutes" json:"session_max_age_minutes"`
	UpdatedBy            *uuid.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertTeamIdentityPolicy(ctx context.Context, arg UpsertTeamIdentityPolicyParams) (TeamIdentityPolicy, error) {
	row := q.db.QueryRow(ctx, upsertTeamIdentityPolicy,
		arg.TeamID,
		arg.RequireMfa,
		arg.SessionMaxAgeMinutes,
		arg.UpdatedBy,
	)
	var i TeamIdentityPolicy
	err := row.Scan(
		&i.TeamID,
		&i.RequireMfa,
		&i.SessionMaxAgeMinutes,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
