// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInboxMessage = `-- name: CreateInboxMessage :one
INSERT INTO inbox_messages (
    team_id, category, priority, title, body, data, actions, source, source_id
)
SELECT
    team.id, $1, $2, $3,
    $4, $5, $6, $7,
    $8
FROM teams AS team
WHERE team.id = $9
  AND team.status = 'active'
RETURNING id, team_id, category, priority, title, body, data, actions, source, source_id, created_at, updated_at
`

type CreateInboxMessageParams struct {
	Category string     `db:"category" json:"category"`
	Priority string     `db:"priority" json:"priority"`
	Title    string     `db:"title" json:"title"`
	Body     string     `db:"body" json:"body"`
	Data     []byte     `db:"data" json:"data"`
	Actions  []byte     `db:"actions" json:"actions"`
	Source   string     `db:"source" json:"source"`
	SourceID *uuid.UUID `db:"source_id" json:"source_id"`
	TeamID   uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateInboxMessage(ctx context.Context, arg CreateInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, createInboxMessage,
		arg.Category,
		arg.Priority,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.Actions,
		arg.Source,
		arg.SourceID,
		arg.TeamID,
	)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Category,
		&i.Priority,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Actions,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT message.id, message.team_id, message.category, message.priority, message.title, message.body, message.data, message.actions, message.source, message.source_id, message.created_at, message.updated_at
FROM inbox_messages AS message
JOIN teams AS team ON team.id = message.team_id
WHERE message.id = $1
  AND message.team_id = $2
  AND team.status = 'active'
`

type GetInboxMessageParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessage, arg.ID, arg.TeamID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Category,
		&i.Priority,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Actions,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboxMessageBySource = `-- name: GetInboxMessageBySource :one
SELECT message.id, message.team_id, message.category, message.priority, message.title, message.body, message.data, message.actions, message.source, message.source_id, message.created_at, message.updated_at
FROM inbox_messages AS message
JOIN teams AS team ON team.id = message.team_id
WHERE message.team_id = $1
  AND message.source = $2
  AND message.source_id = $3
  AND team.status = 'active'
ORDER BY message.created_at DESC
LIMIT 1
`

type GetInboxMessageBySourceParams struct {
	TeamID   uuid.UUID  `db:"team_id" json:"team_id"`
	Source   string     `db:"source" json:"source"`
	SourceID *uuid.UUID `db:"source_id" json:"source_id"`
}

func (q *Queries) GetInboxMessageBySource(ctx context.Context, arg GetInboxMessageBySourceParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessageBySource, arg.TeamID, arg.Source, arg.SourceID)
	var i InboxMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Category,
		&i.Priority,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Actions,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxMessages = `-- name: ListInboxMessages :many
SELECT message.id, message.team_id, message.category, message.priority, message.title, message.body, message.data, message.actions, message.source, message.source_id, message.created_at, message.updated_at
FROM inbox_messages AS message
JOIN teams AS team ON team.id = message.team_id
WHERE message.team_id = $1
  AND team.status = 'active'
ORDER BY message.created_at DESC, message.id DESC
LIMIT $3
OFFSET $2
`

type ListInboxMessagesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListInboxMessages(ctx context.Context, arg ListInboxMessagesParams) ([]InboxMessage, error) {
	rows, err := q.db.Query(ctx, listInboxMessages, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxMessage{}
	for rows.Next() {
		var i InboxMessage
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Category,
			&i.Priority,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Actions,
			&i.Source,
			&i.SourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
