// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_receipts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveInboxReceipt = `-- name: ArchiveInboxReceipt :one
UPDATE inbox_receipts
SET archived_at = COALESCE(archived_at, now()),
    updated_at = now()
WHERE team_id = $1
  AND message_id = $2
  AND recipient_id = $3
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type ArchiveInboxReceiptParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) ArchiveInboxReceipt(ctx context.Context, arg ArchiveInboxReceiptParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, archiveInboxReceipt, arg.TeamID, arg.MessageID, arg.RecipientID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countUnreadInboxReceipts = `-- name: CountUnreadInboxReceipts :one
SELECT count(*)::bigint
FROM inbox_receipts AS receipt
JOIN teams AS team ON team.id = receipt.team_id
WHERE receipt.team_id = $1
  AND receipt.recipient_id = $2
  AND receipt.read_at IS NULL
  AND receipt.archived_at IS NULL
  AND team.status = 'active'
`

type CountUnreadInboxReceiptsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) CountUnreadInboxReceipts(ctx context.Context, arg CountUnreadInboxReceiptsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadInboxReceipts, arg.TeamID, arg.RecipientID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInboxReceipt = `-- name: CreateInboxReceipt :one
INSERT INTO inbox_receipts (team_id, message_id, recipient_id)
SELECT message.team_id, message.id, $1
FROM inbox_messages AS message
WHERE message.id = $2
  AND message.team_id = $3
ON CONFLICT (team_id, message_id, recipient_id) DO UPDATE
SET updated_at = inbox_receipts.updated_at
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type CreateInboxReceiptParams struct {
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateInboxReceipt(ctx context.Context, arg CreateInboxReceiptParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, createInboxReceipt, arg.RecipientID, arg.MessageID, arg.TeamID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInboxReceipts = `-- name: CreateInboxReceipts :many
INSERT INTO inbox_receipts (team_id, message_id, recipient_id)
SELECT message.team_id, message.id, recipient.recipient_id
FROM inbox_messages AS message
CROSS JOIN unnest($1::text[]) AS recipient(recipient_id)
WHERE message.id = $2
  AND message.team_id = $3
ON CONFLICT (team_id, message_id, recipient_id) DO NOTHING
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type CreateInboxReceiptsParams struct {
	RecipientIds []string  `db:"recipient_ids" json:"recipient_ids"`
	MessageID    uuid.UUID `db:"message_id" json:"message_id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateInboxReceipts(ctx context.Context, arg CreateInboxReceiptsParams) ([]InboxReceipt, error) {
	rows, err := q.db.Query(ctx, createInboxReceipts, arg.RecipientIds, arg.MessageID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxReceipt{}
	for rows.Next() {
		var i InboxReceipt
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.MessageID,
			&i.RecipientID,
			&i.SeenAt,
			&i.ReadAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInboxReceipt = `-- name: GetInboxReceipt :one
SELECT receipt.id, receipt.team_id, receipt.message_id, receipt.recipient_id, receipt.seen_at, receipt.read_at, receipt.archived_at, receipt.created_at, receipt.updated_at
FROM inbox_receipts AS receipt
JOIN teams AS team ON team.id = receipt.team_id
WHERE receipt.team_id = $1
  AND receipt.message_id = $2
  AND receipt.recipient_id = $3
  AND team.status = 'active'
`

type GetInboxReceiptParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) GetInboxReceipt(ctx context.Context, arg GetInboxReceiptParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, getInboxReceipt, arg.TeamID, arg.MessageID, arg.RecipientID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInboxFeed = `-- name: ListInboxFeed :many
SELECT
    receipt.id AS receipt_id,
    receipt.recipient_id,
    receipt.seen_at,
    receipt.read_at,
    receipt.archived_at,
    receipt.created_at AS receipt_created_at,
    message.id, message.team_id, message.category, message.priority, message.title, message.body, message.data, message.actions, message.source, message.source_id, message.created_at, message.updated_at
FROM inbox_receipts AS receipt
JOIN inbox_messages AS message
  ON message.id = receipt.message_id
 AND message.team_id = receipt.team_id
JOIN teams AS team ON team.id = receipt.team_id
WHERE receipt.team_id = $1
  AND receipt.recipient_id = $2
  AND receipt.archived_at IS NULL
  AND team.status = 'active'
ORDER BY receipt.created_at DESC, receipt.id DESC
LIMIT $4
OFFSET $3
`

type ListInboxFeedParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

type ListInboxFeedRow struct {
	ReceiptID        uuid.UUID          `db:"receipt_id" json:"receipt_id"`
	RecipientID      string             `db:"recipient_id" json:"recipient_id"`
	SeenAt           pgtype.Timestamptz `db:"seen_at" json:"seen_at"`
	ReadAt           pgtype.Timestamptz `db:"read_at" json:"read_at"`
	ArchivedAt       pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	ReceiptCreatedAt pgtype.Timestamptz `db:"receipt_created_at" json:"receipt_created_at"`
	ID               uuid.UUID          `db:"id" json:"id"`
	TeamID           uuid.UUID          `db:"team_id" json:"team_id"`
	Category         string             `db:"category" json:"category"`
	Priority         string             `db:"priority" json:"priority"`
	Title            string             `db:"title" json:"title"`
	Body             string             `db:"body" json:"body"`
	Data             []byte             `db:"data" json:"data"`
	Actions          []byte             `db:"actions" json:"actions"`
	Source           string             `db:"source" json:"source"`
	SourceID         *uuid.UUID         `db:"source_id" json:"source_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListInboxFeed(ctx context.Context, arg ListInboxFeedParams) ([]ListInboxFeedRow, error) {
	rows, err := q.db.Query(ctx, listInboxFeed,
		arg.TeamID,
		arg.RecipientID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxFeedRow{}
	for rows.Next() {
		var i ListInboxFeedRow
		if err := rows.Scan(
			&i.ReceiptID,
			&i.RecipientID,
			&i.SeenAt,
			&i.ReadAt,
			&i.ArchivedAt,
			&i.ReceiptCreatedAt,
			&i.ID,
			&i.TeamID,
			&i.Category,
			&i.Priority,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.Actions,
			&i.Source,
			&i.SourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxReceiptRead = `-- name: MarkInboxReceiptRead :one
UPDATE inbox_receipts
SET seen_at = COALESCE(seen_at, now()),
    read_at = COALESCE(read_at, now()),
    updated_at = now()
WHERE team_id = $1
  AND message_id = $2
  AND recipient_id = $3
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type MarkInboxReceiptReadParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) MarkInboxReceiptRead(ctx context.Context, arg MarkInboxReceiptReadParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, markInboxReceiptRead, arg.TeamID, arg.MessageID, arg.RecipientID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markInboxReceiptSeen = `-- name: MarkInboxReceiptSeen :one
UPDATE inbox_receipts
SET seen_at = COALESCE(seen_at, now()),
    updated_at = now()
WHERE team_id = $1
  AND message_id = $2
  AND recipient_id = $3
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type MarkInboxReceiptSeenParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) MarkInboxReceiptSeen(ctx context.Context, arg MarkInboxReceiptSeenParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, markInboxReceiptSeen, arg.TeamID, arg.MessageID, arg.RecipientID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveInboxReceipt = `-- name: UnarchiveInboxReceipt :one
UPDATE inbox_receipts
SET archived_at = NULL,
    updated_at = now()
WHERE team_id = $1
  AND message_id = $2
  AND recipient_id = $3
RETURNING id, team_id, message_id, recipient_id, seen_at, read_at, archived_at, created_at, updated_at
`

type UnarchiveInboxReceiptParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	MessageID   uuid.UUID `db:"message_id" json:"message_id"`
	RecipientID string    `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) UnarchiveInboxReceipt(ctx context.Context, arg UnarchiveInboxReceiptParams) (InboxReceipt, error) {
	row := q.db.QueryRow(ctx, unarchiveInboxReceipt, arg.TeamID, arg.MessageID, arg.RecipientID)
	var i InboxReceipt
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.MessageID,
		&i.RecipientID,
		&i.SeenAt,
		&i.ReadAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
