// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTOTPCredential = `-- name: ConfirmTOTPCredential :execrows
UPDATE totp_credentials
SET verified_at = now(),
    last_used_step = $1,
    updated_at = now()
WHERE user_id = $2
  AND verified_at IS NULL
`

type ConfirmTOTPCredentialParams struct {
	LastUsedStep *int64    `db:"last_used_step" json:"last_used_step"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ConfirmTOTPCredential(ctx context.Context, arg ConfirmTOTPCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmTOTPCredential, arg.LastUsedStep, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash)
VALUES ($1, $2)
`

type CreateRecoveryCodeParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	CodeHash string    `db:"code_hash" json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes
WHERE user_id = $1
`

type DeleteRecoveryCodesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, arg DeleteRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, arg.UserID)
	return err
}

const deleteTOTPCredential = `-- name: DeleteTOTPCredential :exec
DELETE FROM totp_credentials
WHERE user_id = $1
`

type DeleteTOTPCredentialParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteTOTPCredential(ctx context.Context, arg DeleteTOTPCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteTOTPCredential, arg.UserID)
	return err
}

const downgradeSessionAfterMFADisable = `-- name: DowngradeSessionAfterMFADisable :exec
UPDATE sessions
SET authentication_method = 'password',
    assurance_level = 'aal1',
    mfa_completed_at = NULL
WHERE user_id = $1
  AND id = $2
`

type DowngradeSessionAfterMFADisableParams struct {
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	CurrentSessionID string    `db:"current_session_id" json:"current_session_id"`
}

func (q *Queries) DowngradeSessionAfterMFADisable(ctx context.Context, arg DowngradeSessionAfterMFADisableParams) error {
	_, err := q.db.Exec(ctx, downgradeSessionAfterMFADisable, arg.UserID, arg.CurrentSessionID)
	return err
}

const elevateSessionAfterMFAEnrollment = `-- name: ElevateSessionAfterMFAEnrollment :execrows
UPDATE sessions
SET assurance_level = 'aal2',
    mfa_completed_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type ElevateSessionAfterMFAEnrollmentParams struct {
	SessionID string    `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ElevateSessionAfterMFAEnrollment(ctx context.Context, arg ElevateSessionAfterMFAEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, elevateSessionAfterMFAEnrollment, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTOTPCredential = `-- name: GetTOTPCredential :one
SELECT secret_ciphertext, verified_at, last_used_step
FROM totp_credentials
WHERE user_id = $1
`

type GetTOTPCredentialParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetTOTPCredentialRow struct {
	SecretCiphertext []byte             `db:"secret_ciphertext" json:"secret_ciphertext"`
	VerifiedAt       pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	LastUsedStep     *int64             `db:"last_used_step" json:"last_used_step"`
}

func (q *Queries) GetTOTPCredential(ctx context.Context, arg GetTOTPCredentialParams) (GetTOTPCredentialRow, error) {
	row := q.db.QueryRow(ctx, getTOTPCredential, arg.UserID)
	var i GetTOTPCredentialRow
	err := row.Scan(&i.SecretCiphertext, &i.VerifiedAt, &i.LastUsedStep)
	return i, err
}

const isTOTPEnabled = `-- name: IsTOTPEnabled :one
SELECT EXISTS (
    SELECT 1
    FROM totp_credentials
    WHERE user_id = $1
      AND verified_at IS NOT NULL
)
`

type IsTOTPEnabledParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) IsTOTPEnabled(ctx context.Context, arg IsTOTPEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTOTPEnabled, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const putUnverifiedTOTPCredential = `-- name: PutUnverifiedTOTPCredential :execrows
INSERT INTO totp_credentials (user_id, secret_ciphertext)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
    secret_ciphertext = EXCLUDED.secret_ciphertext,
    verified_at = NULL,
    last_used_step = NULL,
    updated_at = now()
WHERE totp_credentials.verified_at IS NULL
`

type PutUnverifiedTOTPCredentialParams struct {
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	SecretCiphertext []byte    `db:"secret_ciphertext" json:"secret_ciphertext"`
}

func (q *Queries) PutUnverifiedTOTPCredential(ctx context.Context, arg PutUnverifiedTOTPCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, putUnverifiedTOTPCredential, arg.UserID, arg.SecretCiphertext)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherSessionsAfterMFADisable = `-- name: RevokeOtherSessionsAfterMFADisable :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND id <> $2
  AND revoked_at IS NULL
`

type RevokeOtherSessionsAfterMFADisableParams struct {
	UserID           uuid.UUID `db:"user_id" json:"user_id"`
	CurrentSessionID string    `db:"current_session_id" json:"current_session_id"`
}

func (q *Queries) RevokeOtherSessionsAfterMFADisable(ctx context.Context, arg RevokeOtherSessionsAfterMFADisableParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessionsAfterMFADisable, arg.UserID, arg.CurrentSessionID)
	return err
}

const useRecoveryCodeAndElevateSession = `-- name: UseRecoveryCodeAndElevateSession :execrows
WITH accepted AS (
    UPDATE recovery_codes
    SET used_at = now()
    WHERE user_id = $2
      AND code_hash = $3
      AND used_at IS NULL
    RETURNING user_id
)
UPDATE sessions
SET authentication_method = 'recovery_code',
    assurance_level = 'aal2',
    mfa_completed_at = now()
WHERE sessions.id = $1
  AND sessions.user_id = $2
  AND sessions.revoked_at IS NULL
  AND EXISTS (SELECT 1 FROM accepted)
`

type UseRecoveryCodeAndElevateSessionParams struct {
	SessionID string    `db:"session_id" json:"session_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	CodeHash  string    `db:"code_hash" json:"code_hash"`
}

func (q *Queries) UseRecoveryCodeAndElevateSession(ctx context.Context, arg UseRecoveryCodeAndElevateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCodeAndElevateSession, arg.SessionID, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const verifyTOTPAndElevateSession = `-- name: VerifyTOTPAndElevateSession :execrows
WITH accepted AS (
    UPDATE totp_credentials
    SET last_used_step = $3,
        updated_at = now()
    WHERE user_id = $2
      AND verified_at IS NOT NULL
      AND (last_used_step IS NULL OR last_used_step < $3)
    RETURNING user_id
)
UPDATE sessions
SET assurance_level = 'aal2',
    mfa_completed_at = now()
WHERE sessions.id = $1
  AND sessions.user_id = $2
  AND sessions.revoked_at IS NULL
  AND EXISTS (SELECT 1 FROM accepted)
`

type VerifyTOTPAndElevateSessionParams struct {
	SessionID    string    `db:"session_id" json:"session_id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	LastUsedStep *int64    `db:"last_used_step" json:"last_used_step"`
}

func (q *Queries) VerifyTOTPAndElevateSession(ctx context.Context, arg VerifyTOTPAndElevateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, verifyTOTPAndElevateSession, arg.SessionID, arg.UserID, arg.LastUsedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
