// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailMessage struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
	SenderDomainID    *uuid.UUID         `db:"sender_domain_id" json:"sender_domain_id"`
	DeliveryProvider  string             `db:"delivery_provider" json:"delivery_provider"`
	ProviderRegion    string             `db:"provider_region" json:"provider_region"`
	MessageType       string             `db:"message_type" json:"message_type"`
	FromEmail         string             `db:"from_email" json:"from_email"`
	FromName          *string            `db:"from_name" json:"from_name"`
	ReplyToEmail      *string            `db:"reply_to_email" json:"reply_to_email"`
	ToEmail           string             `db:"to_email" json:"to_email"`
	ToName            *string            `db:"to_name" json:"to_name"`
	Subject           string             `db:"subject" json:"subject"`
	HtmlBody          *string            `db:"html_body" json:"html_body"`
	TextBody          *string            `db:"text_body" json:"text_body"`
	Status            string             `db:"status" json:"status"`
	Provider          *string            `db:"provider" json:"provider"`
	ProviderMessageID *string            `db:"provider_message_id" json:"provider_message_id"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	QueuedAt          pgtype.Timestamptz `db:"queued_at" json:"queued_at"`
	ProcessingAt      pgtype.Timestamptz `db:"processing_at" json:"processing_at"`
	SubmittedAt       pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt       pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	FailedAt          pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Recipients        []byte             `db:"recipients" json:"recipients"`
	Headers           []byte             `db:"headers" json:"headers"`
	Attachments       []byte             `db:"attachments" json:"attachments"`
	Tags              []byte             `db:"tags" json:"tags"`
	ScheduledAt       pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
}

type IdempotencyKey struct {
	Scope               string             `db:"scope" json:"scope"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	Method              string             `db:"method" json:"method"`
	Path                string             `db:"path" json:"path"`
	RequestHash         string             `db:"request_hash" json:"request_hash"`
	Status              string             `db:"status" json:"status"`
	ResponseStatus      *int32             `db:"response_status" json:"response_status"`
	ResponseBody        []byte             `db:"response_body" json:"response_body"`
	ResponseContentType *string            `db:"response_content_type" json:"response_content_type"`
	ResponseHeaders     []byte             `db:"response_headers" json:"response_headers"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OauthIdentity struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	UserID      uuid.UUID          `db:"user_id" json:"user_id"`
	Provider    string             `db:"provider" json:"provider"`
	ProviderUid string             `db:"provider_uid" json:"provider_uid"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Subject       string             `db:"subject" json:"subject"`
	AggregateType string             `db:"aggregate_type" json:"aggregate_type"`
	AggregateID   uuid.UUID          `db:"aggregate_id" json:"aggregate_id"`
	Payload       []byte             `db:"payload" json:"payload"`
	Headers       []byte             `db:"headers" json:"headers"`
	AvailableAt   pgtype.Timestamptz `db:"available_at" json:"available_at"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attempts      int32              `db:"attempts" json:"attempts"`
	LastError     *string            `db:"last_error" json:"last_error"`
	LockedAt      pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy      *string            `db:"locked_by" json:"locked_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProcessedEvent struct {
	ConsumerName string             `db:"consumer_name" json:"consumer_name"`
	EventID      uuid.UUID          `db:"event_id" json:"event_id"`
	ProcessedAt  pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
}

type SenderDomain struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Domain              string             `db:"domain" json:"domain"`
	Provider            string             `db:"provider" json:"provider"`
	ProviderRegion      string             `db:"provider_region" json:"provider_region"`
	Status              string             `db:"status" json:"status"`
	VerificationRecords []byte             `db:"verification_records" json:"verification_records"`
	FailureReason       *string            `db:"failure_reason" json:"failure_reason"`
	LastCheckedAt       pgtype.Timestamptz `db:"last_checked_at" json:"last_checked_at"`
	VerifiedAt          pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	CreatedBy           *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SenderID struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	TeamID          uuid.UUID          `db:"team_id" json:"team_id"`
	Name            string             `db:"name" json:"name"`
	CountryCode     string             `db:"country_code" json:"country_code"`
	Purpose         string             `db:"purpose" json:"purpose"`
	Status          string             `db:"status" json:"status"`
	Provider        *string            `db:"provider" json:"provider"`
	RejectionReason *string            `db:"rejection_reason" json:"rejection_reason"`
	ApprovedAt      pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	RejectedAt      pgtype.Timestamptz `db:"rejected_at" json:"rejected_at"`
	SuspendedAt     pgtype.Timestamptz `db:"suspended_at" json:"suspended_at"`
	CreatedBy       *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID         string             `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	UserAgent  *string            `db:"user_agent" json:"user_agent"`
	IpAddress  *string            `db:"ip_address" json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

type SmsMessage struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	TeamID             uuid.UUID          `db:"team_id" json:"team_id"`
	SenderID           *uuid.UUID         `db:"sender_id" json:"sender_id"`
	ToNumber           string             `db:"to_number" json:"to_number"`
	FromName           string             `db:"from_name" json:"from_name"`
	Body               string             `db:"body" json:"body"`
	Status             string             `db:"status" json:"status"`
	ProviderID         *string            `db:"provider_id" json:"provider_id"`
	ProviderMessageID  *string            `db:"provider_message_id" json:"provider_message_id"`
	Segments           int32              `db:"segments" json:"segments"`
	CostMicros         int64              `db:"cost_micros" json:"cost_micros"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	Tags               []byte             `db:"tags" json:"tags"`
	ScheduledAt        pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	SubmittedAt        pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	DeliveredAt        pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PricingRuleID      uuid.UUID          `db:"pricing_rule_id" json:"pricing_rule_id"`
	UnitCostMicros     int64              `db:"unit_cost_micros" json:"unit_cost_micros"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
}

type SmsPricingAuditLog struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	ActorUserID  *uuid.UUID         `db:"actor_user_id" json:"actor_user_id"`
	ActorEmail   string             `db:"actor_email" json:"actor_email"`
	Action       string             `db:"action" json:"action"`
	ResourceType string             `db:"resource_type" json:"resource_type"`
	ResourceID   *uuid.UUID         `db:"resource_id" json:"resource_id"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SmsPricingPlan struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Currency  string             `db:"currency" json:"currency"`
	IsDefault bool               `db:"is_default" json:"is_default"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type SmsPricingRule struct {
	ID                 uuid.UUID          `db:"id" json:"id"`
	PricingPlanID      uuid.UUID          `db:"pricing_plan_id" json:"pricing_plan_id"`
	UnitCostMicros     int64              `db:"unit_cost_micros" json:"unit_cost_micros"`
	EffectiveFrom      pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil     pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	Status             string             `db:"status" json:"status"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DestinationCountry string             `db:"destination_country" json:"destination_country"`
}

type Team struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedBy *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamInvitation struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	Email      string             `db:"email" json:"email"`
	Role       string             `db:"role" json:"role"`
	Status     string             `db:"status" json:"status"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	InvitedBy  *uuid.UUID         `db:"invited_by" json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `db:"accepted_at" json:"accepted_at"`
	DeclinedAt pgtype.Timestamptz `db:"declined_at" json:"declined_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamMember struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamSmsSetting struct {
	TeamID        uuid.UUID          `db:"team_id" json:"team_id"`
	PricingPlanID uuid.UUID          `db:"pricing_plan_id" json:"pricing_plan_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TeamToken struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Permissions []string           `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	Name          string             `db:"name" json:"name"`
	PasswordHash  *string            `db:"password_hash" json:"password_hash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type VerificationToken struct {
	Identifier string             `db:"identifier" json:"identifier"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Wallet struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	Currency  string             `db:"currency" json:"currency"`
	Balance   int64              `db:"balance" json:"balance"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WalletTransaction struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	WalletID        uuid.UUID          `db:"wallet_id" json:"wallet_id"`
	TeamID          uuid.UUID          `db:"team_id" json:"team_id"`
	TransactionType string             `db:"transaction_type" json:"transaction_type"`
	ReferenceID     *uuid.UUID         `db:"reference_id" json:"reference_id"`
	Amount          int64              `db:"amount" json:"amount"`
	BalanceAfter    int64              `db:"balance_after" json:"balance_after"`
	Status          string             `db:"status" json:"status"`
	Description     *string            `db:"description" json:"description"`
	Metadata        []byte             `db:"metadata" json:"metadata"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	EventID        uuid.UUID          `db:"event_id" json:"event_id"`
	EndpointID     uuid.UUID          `db:"endpoint_id" json:"endpoint_id"`
	Status         string             `db:"status" json:"status"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	ResponseStatus *int32             `db:"response_status" json:"response_status"`
	ResponseBody   *string            `db:"response_body" json:"response_body"`
	LastError      *string            `db:"last_error" json:"last_error"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	LockedAt       pgtype.Timestamptz `db:"locked_at" json:"locked_at"`
	LockedBy       *string            `db:"locked_by" json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WebhookEndpoint struct {
	ID                  uuid.UUID          `db:"id" json:"id"`
	TeamID              uuid.UUID          `db:"team_id" json:"team_id"`
	Url                 string             `db:"url" json:"url"`
	SigningSecret       []byte             `db:"signing_secret" json:"signing_secret"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	SubscribedEvents    []string           `db:"subscribed_events" json:"subscribed_events"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt          pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	ConsecutiveFailures int32              `db:"consecutive_failures" json:"consecutive_failures"`
	LastFailureAt       pgtype.Timestamptz `db:"last_failure_at" json:"last_failure_at"`
	DisabledReason      *string            `db:"disabled_reason" json:"disabled_reason"`
}

type WebhookEvent struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ObjectType string             `db:"object_type" json:"object_type"`
	ObjectID   *uuid.UUID         `db:"object_id" json:"object_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
