// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_workflows.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createNotificationWorkflow = `-- name: CreateNotificationWorkflow :one
INSERT INTO notification_workflows (
    team_id, key, name, category, enabled
)
SELECT
    team.id, $1, $2, $3, $4
FROM teams AS team
WHERE team.id = $5
  AND team.status = 'active'
RETURNING id, team_id, key, name, category, enabled, published_version_id, created_at, updated_at
`

type CreateNotificationWorkflowParams struct {
	Key      string    `db:"key" json:"key"`
	Name     string    `db:"name" json:"name"`
	Category string    `db:"category" json:"category"`
	Enabled  bool      `db:"enabled" json:"enabled"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateNotificationWorkflow(ctx context.Context, arg CreateNotificationWorkflowParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, createNotificationWorkflow,
		arg.Key,
		arg.Name,
		arg.Category,
		arg.Enabled,
		arg.TeamID,
	)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationWorkflow = `-- name: GetNotificationWorkflow :one
SELECT workflow.id, workflow.team_id, workflow.key, workflow.name, workflow.category, workflow.enabled, workflow.published_version_id, workflow.created_at, workflow.updated_at
FROM notification_workflows AS workflow
JOIN teams AS team ON team.id = workflow.team_id
WHERE workflow.id = $1
  AND workflow.team_id = $2
  AND team.status = 'active'
`

type GetNotificationWorkflowParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationWorkflow(ctx context.Context, arg GetNotificationWorkflowParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflow, arg.ID, arg.TeamID)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationWorkflowByKey = `-- name: GetNotificationWorkflowByKey :one
SELECT workflow.id, workflow.team_id, workflow.key, workflow.name, workflow.category, workflow.enabled, workflow.published_version_id, workflow.created_at, workflow.updated_at
FROM notification_workflows AS workflow
JOIN teams AS team ON team.id = workflow.team_id
WHERE workflow.team_id = $1
  AND workflow.key = $2
  AND team.status = 'active'
`

type GetNotificationWorkflowByKeyParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Key    string    `db:"key" json:"key"`
}

func (q *Queries) GetNotificationWorkflowByKey(ctx context.Context, arg GetNotificationWorkflowByKeyParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflowByKey, arg.TeamID, arg.Key)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationWorkflowForUpdate = `-- name: GetNotificationWorkflowForUpdate :one
SELECT id, team_id, key, name, category, enabled, published_version_id, created_at, updated_at
FROM notification_workflows
WHERE id = $1
  AND team_id = $2
FOR UPDATE
`

type GetNotificationWorkflowForUpdateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationWorkflowForUpdate(ctx context.Context, arg GetNotificationWorkflowForUpdateParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflowForUpdate, arg.ID, arg.TeamID)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationWorkflows = `-- name: ListNotificationWorkflows :many
SELECT workflow.id, workflow.team_id, workflow.key, workflow.name, workflow.category, workflow.enabled, workflow.published_version_id, workflow.created_at, workflow.updated_at
FROM notification_workflows AS workflow
JOIN teams AS team ON team.id = workflow.team_id
WHERE workflow.team_id = $1
  AND team.status = 'active'
ORDER BY workflow.created_at DESC, workflow.id DESC
LIMIT $3
OFFSET $2
`

type ListNotificationWorkflowsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListNotificationWorkflows(ctx context.Context, arg ListNotificationWorkflowsParams) ([]NotificationWorkflow, error) {
	rows, err := q.db.Query(ctx, listNotificationWorkflows, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationWorkflow{}
	for rows.Next() {
		var i NotificationWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.Name,
			&i.Category,
			&i.Enabled,
			&i.PublishedVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationWorkflowPublishedVersion = `-- name: SetNotificationWorkflowPublishedVersion :one
UPDATE notification_workflows
SET published_version_id = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
RETURNING id, team_id, key, name, category, enabled, published_version_id, created_at, updated_at
`

type SetNotificationWorkflowPublishedVersionParams struct {
	PublishedVersionID *uuid.UUID `db:"published_version_id" json:"published_version_id"`
	ID                 uuid.UUID  `db:"id" json:"id"`
	TeamID             uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) SetNotificationWorkflowPublishedVersion(ctx context.Context, arg SetNotificationWorkflowPublishedVersionParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, setNotificationWorkflowPublishedVersion, arg.PublishedVersionID, arg.ID, arg.TeamID)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationWorkflow = `-- name: UpdateNotificationWorkflow :one
UPDATE notification_workflows AS workflow
SET name = $1,
    category = $2,
    enabled = $3,
    updated_at = now()
FROM teams AS team
WHERE workflow.id = $4
  AND workflow.team_id = $5
  AND team.id = workflow.team_id
  AND team.status = 'active'
RETURNING workflow.id, workflow.team_id, workflow.key, workflow.name, workflow.category, workflow.enabled, workflow.published_version_id, workflow.created_at, workflow.updated_at
`

type UpdateNotificationWorkflowParams struct {
	Name     string    `db:"name" json:"name"`
	Category string    `db:"category" json:"category"`
	Enabled  bool      `db:"enabled" json:"enabled"`
	ID       uuid.UUID `db:"id" json:"id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateNotificationWorkflow(ctx context.Context, arg UpdateNotificationWorkflowParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, updateNotificationWorkflow,
		arg.Name,
		arg.Category,
		arg.Enabled,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.Category,
		&i.Enabled,
		&i.PublishedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
