// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_recipients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationRecipient = `-- name: GetNotificationRecipient :one
SELECT recipient.id, recipient.team_id, recipient.external_id, recipient.email, recipient.phone, recipient.locale, recipient.timezone, recipient.data, recipient.created_at, recipient.updated_at
FROM notification_recipients AS recipient
JOIN teams AS team ON team.id = recipient.team_id
WHERE recipient.id = $1
  AND recipient.team_id = $2
  AND team.status = 'active'
`

type GetNotificationRecipientParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationRecipient(ctx context.Context, arg GetNotificationRecipientParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, getNotificationRecipient, arg.ID, arg.TeamID)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ExternalID,
		&i.Email,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationRecipientByExternalID = `-- name: GetNotificationRecipientByExternalID :one
SELECT recipient.id, recipient.team_id, recipient.external_id, recipient.email, recipient.phone, recipient.locale, recipient.timezone, recipient.data, recipient.created_at, recipient.updated_at
FROM notification_recipients AS recipient
JOIN teams AS team ON team.id = recipient.team_id
WHERE recipient.team_id = $1
  AND recipient.external_id = $2
  AND team.status = 'active'
`

type GetNotificationRecipientByExternalIDParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	ExternalID string    `db:"external_id" json:"external_id"`
}

func (q *Queries) GetNotificationRecipientByExternalID(ctx context.Context, arg GetNotificationRecipientByExternalIDParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, getNotificationRecipientByExternalID, arg.TeamID, arg.ExternalID)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ExternalID,
		&i.Email,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationRecipients = `-- name: ListNotificationRecipients :many
SELECT recipient.id, recipient.team_id, recipient.external_id, recipient.email, recipient.phone, recipient.locale, recipient.timezone, recipient.data, recipient.created_at, recipient.updated_at
FROM notification_recipients AS recipient
JOIN teams AS team ON team.id = recipient.team_id
WHERE recipient.team_id = $1
  AND team.status = 'active'
ORDER BY recipient.created_at DESC, recipient.id DESC
LIMIT $3
OFFSET $2
`

type ListNotificationRecipientsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListNotificationRecipients(ctx context.Context, arg ListNotificationRecipientsParams) ([]NotificationRecipient, error) {
	rows, err := q.db.Query(ctx, listNotificationRecipients, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRecipient{}
	for rows.Next() {
		var i NotificationRecipient
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ExternalID,
			&i.Email,
			&i.Phone,
			&i.Locale,
			&i.Timezone,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationRecipient = `-- name: UpdateNotificationRecipient :one
UPDATE notification_recipients AS recipient
SET email = $1,
    phone = $2,
    locale = $3,
    timezone = $4,
    data = $5,
    updated_at = now()
FROM teams AS team
WHERE recipient.id = $6
  AND recipient.team_id = $7
  AND team.id = recipient.team_id
  AND team.status = 'active'
RETURNING recipient.id, recipient.team_id, recipient.external_id, recipient.email, recipient.phone, recipient.locale, recipient.timezone, recipient.data, recipient.created_at, recipient.updated_at
`

type UpdateNotificationRecipientParams struct {
	Email    *string   `db:"email" json:"email"`
	Phone    *string   `db:"phone" json:"phone"`
	Locale   *string   `db:"locale" json:"locale"`
	Timezone *string   `db:"timezone" json:"timezone"`
	Data     []byte    `db:"data" json:"data"`
	ID       uuid.UUID `db:"id" json:"id"`
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateNotificationRecipient(ctx context.Context, arg UpdateNotificationRecipientParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, updateNotificationRecipient,
		arg.Email,
		arg.Phone,
		arg.Locale,
		arg.Timezone,
		arg.Data,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ExternalID,
		&i.Email,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationRecipient = `-- name: UpsertNotificationRecipient :one
INSERT INTO notification_recipients (
    team_id, external_id, email, phone, locale, timezone, data
)
SELECT
    team.id, $1, $2, $3,
    $4, $5, $6
FROM teams AS team
WHERE team.id = $7
  AND team.status = 'active'
ON CONFLICT (team_id, external_id) DO UPDATE
SET email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    locale = EXCLUDED.locale,
    timezone = EXCLUDED.timezone,
    data = EXCLUDED.data,
    updated_at = now()
RETURNING id, team_id, external_id, email, phone, locale, timezone, data, created_at, updated_at
`

type UpsertNotificationRecipientParams struct {
	ExternalID string    `db:"external_id" json:"external_id"`
	Email      *string   `db:"email" json:"email"`
	Phone      *string   `db:"phone" json:"phone"`
	Locale     *string   `db:"locale" json:"locale"`
	Timezone   *string   `db:"timezone" json:"timezone"`
	Data       []byte    `db:"data" json:"data"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpsertNotificationRecipient(ctx context.Context, arg UpsertNotificationRecipientParams) (NotificationRecipient, error) {
	row := q.db.QueryRow(ctx, upsertNotificationRecipient,
		arg.ExternalID,
		arg.Email,
		arg.Phone,
		arg.Locale,
		arg.Timezone,
		arg.Data,
		arg.TeamID,
	)
	var i NotificationRecipient
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ExternalID,
		&i.Email,
		&i.Phone,
		&i.Locale,
		&i.Timezone,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
