// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_workflow_versions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationWorkflowVersion = `-- name: CreateNotificationWorkflowVersion :one
INSERT INTO notification_workflow_versions (
    team_id, workflow_id, version, status, definition, published_at
)
SELECT
    workflow.team_id,
    workflow.id,
    $1,
    $2,
    $3,
    $4
FROM notification_workflows AS workflow
WHERE workflow.id = $5
  AND workflow.team_id = $6
RETURNING id, team_id, workflow_id, version, status, definition, created_at, published_at
`

type CreateNotificationWorkflowVersionParams struct {
	Version     int32              `db:"version" json:"version"`
	Status      string             `db:"status" json:"status"`
	Definition  []byte             `db:"definition" json:"definition"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	WorkflowID  uuid.UUID          `db:"workflow_id" json:"workflow_id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateNotificationWorkflowVersion(ctx context.Context, arg CreateNotificationWorkflowVersionParams) (NotificationWorkflowVersion, error) {
	row := q.db.QueryRow(ctx, createNotificationWorkflowVersion,
		arg.Version,
		arg.Status,
		arg.Definition,
		arg.PublishedAt,
		arg.WorkflowID,
		arg.TeamID,
	)
	var i NotificationWorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getNotificationWorkflowVersion = `-- name: GetNotificationWorkflowVersion :one
SELECT version.id, version.team_id, version.workflow_id, version.version, version.status, version.definition, version.created_at, version.published_at
FROM notification_workflow_versions AS version
JOIN teams AS team ON team.id = version.team_id
WHERE version.id = $1
  AND version.team_id = $2
  AND team.status = 'active'
`

type GetNotificationWorkflowVersionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationWorkflowVersion(ctx context.Context, arg GetNotificationWorkflowVersionParams) (NotificationWorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflowVersion, arg.ID, arg.TeamID)
	var i NotificationWorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getPublishedNotificationWorkflowVersion = `-- name: GetPublishedNotificationWorkflowVersion :one
SELECT version.id, version.team_id, version.workflow_id, version.version, version.status, version.definition, version.created_at, version.published_at
FROM notification_workflow_versions AS version
JOIN notification_workflows AS workflow
  ON workflow.id = version.workflow_id
 AND workflow.team_id = version.team_id
JOIN teams AS team ON team.id = version.team_id
WHERE workflow.id = $1
  AND workflow.team_id = $2
  AND workflow.enabled = true
  AND version.id = workflow.published_version_id
  AND version.status = 'published'
  AND team.status = 'active'
`

type GetPublishedNotificationWorkflowVersionParams struct {
	WorkflowID uuid.UUID `db:"workflow_id" json:"workflow_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetPublishedNotificationWorkflowVersion(ctx context.Context, arg GetPublishedNotificationWorkflowVersionParams) (NotificationWorkflowVersion, error) {
	row := q.db.QueryRow(ctx, getPublishedNotificationWorkflowVersion, arg.WorkflowID, arg.TeamID)
	var i NotificationWorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listNotificationWorkflowVersions = `-- name: ListNotificationWorkflowVersions :many
SELECT id, team_id, workflow_id, version, status, definition, created_at, published_at
FROM notification_workflow_versions
WHERE workflow_id = $1
  AND team_id = $2
ORDER BY version DESC
`

type ListNotificationWorkflowVersionsParams struct {
	WorkflowID uuid.UUID `db:"workflow_id" json:"workflow_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListNotificationWorkflowVersions(ctx context.Context, arg ListNotificationWorkflowVersionsParams) ([]NotificationWorkflowVersion, error) {
	rows, err := q.db.Query(ctx, listNotificationWorkflowVersions, arg.WorkflowID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationWorkflowVersion{}
	for rows.Next() {
		var i NotificationWorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.WorkflowID,
			&i.Version,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishNotificationWorkflowVersion = `-- name: PublishNotificationWorkflowVersion :one
UPDATE notification_workflow_versions
SET status = 'published',
    published_at = COALESCE(published_at, now())
WHERE id = $1
  AND workflow_id = $2
  AND team_id = $3
  AND status = 'draft'
RETURNING id, team_id, workflow_id, version, status, definition, created_at, published_at
`

type PublishNotificationWorkflowVersionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	WorkflowID uuid.UUID `db:"workflow_id" json:"workflow_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) PublishNotificationWorkflowVersion(ctx context.Context, arg PublishNotificationWorkflowVersionParams) (NotificationWorkflowVersion, error) {
	row := q.db.QueryRow(ctx, publishNotificationWorkflowVersion, arg.ID, arg.WorkflowID, arg.TeamID)
	var i NotificationWorkflowVersion
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.Version,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const retirePublishedNotificationWorkflowVersion = `-- name: RetirePublishedNotificationWorkflowVersion :many
UPDATE notification_workflow_versions
SET status = 'retired'
WHERE workflow_id = $1
  AND team_id = $2
  AND status = 'published'
  AND id <> $3
RETURNING id, team_id, workflow_id, version, status, definition, created_at, published_at
`

type RetirePublishedNotificationWorkflowVersionParams struct {
	WorkflowID uuid.UUID `db:"workflow_id" json:"workflow_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	ExceptID   uuid.UUID `db:"except_id" json:"except_id"`
}

func (q *Queries) RetirePublishedNotificationWorkflowVersion(ctx context.Context, arg RetirePublishedNotificationWorkflowVersionParams) ([]NotificationWorkflowVersion, error) {
	rows, err := q.db.Query(ctx, retirePublishedNotificationWorkflowVersion, arg.WorkflowID, arg.TeamID, arg.ExceptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationWorkflowVersion{}
	for rows.Next() {
		var i NotificationWorkflowVersion
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.WorkflowID,
			&i.Version,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
