// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_step_runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingNotificationSteps = `-- name: CancelPendingNotificationSteps :many
UPDATE notification_step_runs
SET status = 'canceled',
    updated_at = now()
WHERE run_id = $1
  AND team_id = $2
  AND status IN ('pending', 'waiting')
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CancelPendingNotificationStepsParams struct {
	RunID  uuid.UUID `db:"run_id" json:"run_id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CancelPendingNotificationSteps(ctx context.Context, arg CancelPendingNotificationStepsParams) ([]NotificationStepRun, error) {
	rows, err := q.db.Query(ctx, cancelPendingNotificationSteps, arg.RunID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationStepRun{}
	for rows.Next() {
		var i NotificationStepRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RunID,
			&i.StepKey,
			&i.StepType,
			&i.Channel,
			&i.Sequence,
			&i.Status,
			&i.AttemptCount,
			&i.AvailableAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.EmailMessageID,
			&i.SmsMessageID,
			&i.InboxMessageID,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimRunnableNotificationStepRuns = `-- name: ClaimRunnableNotificationStepRuns :many
WITH candidates AS (
    SELECT step.id
    FROM notification_step_runs AS step
    JOIN notification_runs AS run
      ON run.id = step.run_id
     AND run.team_id = step.team_id
    JOIN teams AS team ON team.id = step.team_id
    WHERE step.status IN ('pending', 'waiting')
      AND COALESCE(step.available_at, step.created_at) <= now()
      AND run.status IN ('running', 'waiting')
      AND team.status = 'active'
    ORDER BY COALESCE(step.available_at, step.created_at), step.sequence
    FOR UPDATE OF step SKIP LOCKED
    LIMIT $1
)
UPDATE notification_step_runs AS step
SET status = 'running',
    attempt_count = step.attempt_count + 1,
    started_at = COALESCE(step.started_at, now()),
    updated_at = now()
FROM candidates
WHERE step.id = candidates.id
RETURNING step.id, step.team_id, step.run_id, step.step_key, step.step_type, step.channel, step.sequence, step.status, step.attempt_count, step.available_at, step.started_at, step.completed_at, step.failed_at, step.email_message_id, step.sms_message_id, step.inbox_message_id, step.input, step.output, step.error_code, step.error_message, step.created_at, step.updated_at
`

type ClaimRunnableNotificationStepRunsParams struct {
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ClaimRunnableNotificationStepRuns(ctx context.Context, arg ClaimRunnableNotificationStepRunsParams) ([]NotificationStepRun, error) {
	rows, err := q.db.Query(ctx, claimRunnableNotificationStepRuns, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationStepRun{}
	for rows.Next() {
		var i NotificationStepRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RunID,
			&i.StepKey,
			&i.StepType,
			&i.Channel,
			&i.Sequence,
			&i.Status,
			&i.AttemptCount,
			&i.AvailableAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.EmailMessageID,
			&i.SmsMessageID,
			&i.InboxMessageID,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeNotificationControlStep = `-- name: CompleteNotificationControlStep :one
UPDATE notification_step_runs
SET status = 'completed',
    output = $1,
    completed_at = now(),
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND step_type IN ('delay', 'condition')
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CompleteNotificationControlStepParams struct {
	Output []byte    `db:"output" json:"output"`
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CompleteNotificationControlStep(ctx context.Context, arg CompleteNotificationControlStepParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, completeNotificationControlStep, arg.Output, arg.ID, arg.TeamID)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeNotificationEmailStep = `-- name: CompleteNotificationEmailStep :one
UPDATE notification_step_runs
SET status = 'completed',
    email_message_id = $1,
    output = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND step_type = 'email'
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CompleteNotificationEmailStepParams struct {
	EmailMessageID *uuid.UUID `db:"email_message_id" json:"email_message_id"`
	Output         []byte     `db:"output" json:"output"`
	ID             uuid.UUID  `db:"id" json:"id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CompleteNotificationEmailStep(ctx context.Context, arg CompleteNotificationEmailStepParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, completeNotificationEmailStep,
		arg.EmailMessageID,
		arg.Output,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeNotificationInboxStep = `-- name: CompleteNotificationInboxStep :one
UPDATE notification_step_runs
SET status = 'completed',
    inbox_message_id = $1,
    output = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND step_type = 'inbox'
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CompleteNotificationInboxStepParams struct {
	InboxMessageID *uuid.UUID `db:"inbox_message_id" json:"inbox_message_id"`
	Output         []byte     `db:"output" json:"output"`
	ID             uuid.UUID  `db:"id" json:"id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CompleteNotificationInboxStep(ctx context.Context, arg CompleteNotificationInboxStepParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, completeNotificationInboxStep,
		arg.InboxMessageID,
		arg.Output,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeNotificationSMSStep = `-- name: CompleteNotificationSMSStep :one
UPDATE notification_step_runs
SET status = 'completed',
    sms_message_id = $1,
    output = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND step_type = 'sms'
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CompleteNotificationSMSStepParams struct {
	SmsMessageID *uuid.UUID `db:"sms_message_id" json:"sms_message_id"`
	Output       []byte     `db:"output" json:"output"`
	ID           uuid.UUID  `db:"id" json:"id"`
	TeamID       uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CompleteNotificationSMSStep(ctx context.Context, arg CompleteNotificationSMSStepParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, completeNotificationSMSStep,
		arg.SmsMessageID,
		arg.Output,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationStepRun = `-- name: CreateNotificationStepRun :one
INSERT INTO notification_step_runs (
    team_id, run_id, step_key, step_type, channel, sequence,
    status, available_at, input
)
SELECT
    run.team_id,
    run.id,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
FROM notification_runs AS run
WHERE run.id = $8
  AND run.team_id = $9
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type CreateNotificationStepRunParams struct {
	StepKey     string             `db:"step_key" json:"step_key"`
	StepType    string             `db:"step_type" json:"step_type"`
	Channel     *string            `db:"channel" json:"channel"`
	Sequence    int32              `db:"sequence" json:"sequence"`
	Status      string             `db:"status" json:"status"`
	AvailableAt pgtype.Timestamptz `db:"available_at" json:"available_at"`
	Input       []byte             `db:"input" json:"input"`
	RunID       uuid.UUID          `db:"run_id" json:"run_id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateNotificationStepRun(ctx context.Context, arg CreateNotificationStepRunParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, createNotificationStepRun,
		arg.StepKey,
		arg.StepType,
		arg.Channel,
		arg.Sequence,
		arg.Status,
		arg.AvailableAt,
		arg.Input,
		arg.RunID,
		arg.TeamID,
	)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationStepRun = `-- name: GetNotificationStepRun :one
SELECT id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
FROM notification_step_runs
WHERE id = $1
  AND team_id = $2
`

type GetNotificationStepRunParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationStepRun(ctx context.Context, arg GetNotificationStepRunParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, getNotificationStepRun, arg.ID, arg.TeamID)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationStepRunForUpdate = `-- name: GetNotificationStepRunForUpdate :one
SELECT id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
FROM notification_step_runs
WHERE id = $1
  AND team_id = $2
FOR UPDATE
`

type GetNotificationStepRunForUpdateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationStepRunForUpdate(ctx context.Context, arg GetNotificationStepRunForUpdateParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, getNotificationStepRunForUpdate, arg.ID, arg.TeamID)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationStepRuns = `-- name: ListNotificationStepRuns :many
SELECT id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
FROM notification_step_runs
WHERE run_id = $1
  AND team_id = $2
ORDER BY sequence, created_at, id
`

type ListNotificationStepRunsParams struct {
	RunID  uuid.UUID `db:"run_id" json:"run_id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListNotificationStepRuns(ctx context.Context, arg ListNotificationStepRunsParams) ([]NotificationStepRun, error) {
	rows, err := q.db.Query(ctx, listNotificationStepRuns, arg.RunID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationStepRun{}
	for rows.Next() {
		var i NotificationStepRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RunID,
			&i.StepKey,
			&i.StepType,
			&i.Channel,
			&i.Sequence,
			&i.Status,
			&i.AttemptCount,
			&i.AvailableAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.EmailMessageID,
			&i.SmsMessageID,
			&i.InboxMessageID,
			&i.Input,
			&i.Output,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationStepFailed = `-- name: MarkNotificationStepFailed :one
UPDATE notification_step_runs
SET status = 'failed',
    error_code = $1,
    error_message = $2,
    failed_at = now(),
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type MarkNotificationStepFailedParams struct {
	ErrorCode    *string   `db:"error_code" json:"error_code"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationStepFailed(ctx context.Context, arg MarkNotificationStepFailedParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, markNotificationStepFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationStepWaiting = `-- name: MarkNotificationStepWaiting :one
UPDATE notification_step_runs
SET status = 'waiting',
    available_at = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status = 'running'
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type MarkNotificationStepWaitingParams struct {
	AvailableAt pgtype.Timestamptz `db:"available_at" json:"available_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationStepWaiting(ctx context.Context, arg MarkNotificationStepWaitingParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, markNotificationStepWaiting, arg.AvailableAt, arg.ID, arg.TeamID)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const skipNotificationStep = `-- name: SkipNotificationStep :one
UPDATE notification_step_runs
SET status = 'skipped',
    output = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status IN ('pending', 'waiting')
RETURNING id, team_id, run_id, step_key, step_type, channel, sequence, status, attempt_count, available_at, started_at, completed_at, failed_at, email_message_id, sms_message_id, inbox_message_id, input, output, error_code, error_message, created_at, updated_at
`

type SkipNotificationStepParams struct {
	Output []byte    `db:"output" json:"output"`
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) SkipNotificationStep(ctx context.Context, arg SkipNotificationStepParams) (NotificationStepRun, error) {
	row := q.db.QueryRow(ctx, skipNotificationStep, arg.Output, arg.ID, arg.TeamID)
	var i NotificationStepRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RunID,
		&i.StepKey,
		&i.StepType,
		&i.Channel,
		&i.Sequence,
		&i.Status,
		&i.AttemptCount,
		&i.AvailableAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.EmailMessageID,
		&i.SmsMessageID,
		&i.InboxMessageID,
		&i.Input,
		&i.Output,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
