// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preferences.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteNotificationPreference = `-- name: DeleteNotificationPreference :execrows
DELETE FROM notification_preferences
WHERE id = $1
  AND team_id = $2
  AND recipient_id = $3
`

type DeleteNotificationPreferenceParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	RecipientID uuid.UUID `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) DeleteNotificationPreference(ctx context.Context, arg DeleteNotificationPreferenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotificationPreference, arg.ID, arg.TeamID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT id, team_id, recipient_id, category, workflow_id, channel, enabled, created_at, updated_at
FROM notification_preferences
WHERE team_id = $1
  AND recipient_id = $2
ORDER BY updated_at DESC, id DESC
`

type ListNotificationPreferencesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	RecipientID uuid.UUID `db:"recipient_id" json:"recipient_id"`
}

func (q *Queries) ListNotificationPreferences(ctx context.Context, arg ListNotificationPreferencesParams) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, arg.TeamID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RecipientID,
			&i.Category,
			&i.WorkflowID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveNotificationPreferences = `-- name: ResolveNotificationPreferences :many
SELECT id, team_id, recipient_id, category, workflow_id, channel, enabled, created_at, updated_at
FROM notification_preferences
WHERE team_id = $1
  AND recipient_id = $2
  AND channel = $3
  AND (
      workflow_id = $4
      OR (workflow_id IS NULL AND category = $5)
  )
ORDER BY (workflow_id IS NOT NULL) DESC
`

type ResolveNotificationPreferencesParams struct {
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
	RecipientID uuid.UUID  `db:"recipient_id" json:"recipient_id"`
	Channel     string     `db:"channel" json:"channel"`
	WorkflowID  *uuid.UUID `db:"workflow_id" json:"workflow_id"`
	Category    string     `db:"category" json:"category"`
}

func (q *Queries) ResolveNotificationPreferences(ctx context.Context, arg ResolveNotificationPreferencesParams) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, resolveNotificationPreferences,
		arg.TeamID,
		arg.RecipientID,
		arg.Channel,
		arg.WorkflowID,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RecipientID,
			&i.Category,
			&i.WorkflowID,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryNotificationPreference = `-- name: UpsertCategoryNotificationPreference :one
INSERT INTO notification_preferences (
    team_id, recipient_id, category, workflow_id, channel, enabled
)
SELECT
    recipient.team_id,
    recipient.id,
    $1,
    NULL,
    $2,
    $3
FROM notification_recipients AS recipient
WHERE recipient.id = $4
  AND recipient.team_id = $5
ON CONFLICT (team_id, recipient_id, category, channel)
WHERE workflow_id IS NULL
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    updated_at = now()
RETURNING id, team_id, recipient_id, category, workflow_id, channel, enabled, created_at, updated_at
`

type UpsertCategoryNotificationPreferenceParams struct {
	Category    string    `db:"category" json:"category"`
	Channel     string    `db:"channel" json:"channel"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	RecipientID uuid.UUID `db:"recipient_id" json:"recipient_id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpsertCategoryNotificationPreference(ctx context.Context, arg UpsertCategoryNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertCategoryNotificationPreference,
		arg.Category,
		arg.Channel,
		arg.Enabled,
		arg.RecipientID,
		arg.TeamID,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RecipientID,
		&i.Category,
		&i.WorkflowID,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkflowNotificationPreference = `-- name: UpsertWorkflowNotificationPreference :one
INSERT INTO notification_preferences (
    team_id, recipient_id, category, workflow_id, channel, enabled
)
SELECT
    recipient.team_id,
    recipient.id,
    workflow.category,
    workflow.id,
    $1,
    $2
FROM notification_recipients AS recipient
JOIN notification_workflows AS workflow
  ON workflow.id = $3
 AND workflow.team_id = recipient.team_id
WHERE recipient.id = $4
  AND recipient.team_id = $5
ON CONFLICT (team_id, recipient_id, workflow_id, channel)
WHERE workflow_id IS NOT NULL
DO UPDATE SET
    enabled = EXCLUDED.enabled,
    category = EXCLUDED.category,
    updated_at = now()
RETURNING id, team_id, recipient_id, category, workflow_id, channel, enabled, created_at, updated_at
`

type UpsertWorkflowNotificationPreferenceParams struct {
	Channel     string    `db:"channel" json:"channel"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	WorkflowID  uuid.UUID `db:"workflow_id" json:"workflow_id"`
	RecipientID uuid.UUID `db:"recipient_id" json:"recipient_id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpsertWorkflowNotificationPreference(ctx context.Context, arg UpsertWorkflowNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertWorkflowNotificationPreference,
		arg.Channel,
		arg.Enabled,
		arg.WorkflowID,
		arg.RecipientID,
		arg.TeamID,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RecipientID,
		&i.Category,
		&i.WorkflowID,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
