// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_runs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelNotificationRun = `-- name: CancelNotificationRun :one
UPDATE notification_runs
SET status = 'canceled',
    canceled_at = now(),
    scheduled_at = NULL,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('queued', 'running', 'waiting')
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type CancelNotificationRunParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) CancelNotificationRun(ctx context.Context, arg CancelNotificationRunParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, cancelNotificationRun, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimNotificationRuns = `-- name: ClaimNotificationRuns :many
WITH candidates AS (
    SELECT run.id
    FROM notification_runs AS run
    JOIN teams AS team ON team.id = run.team_id
    WHERE run.status IN ('queued', 'waiting')
      AND COALESCE(run.scheduled_at, run.created_at) <= now()
      AND team.status = 'active'
    ORDER BY COALESCE(run.scheduled_at, run.created_at), run.created_at
    FOR UPDATE OF run SKIP LOCKED
    LIMIT $1
)
UPDATE notification_runs AS run
SET status = 'running',
    started_at = COALESCE(run.started_at, now()),
    updated_at = now()
FROM candidates
WHERE run.id = candidates.id
RETURNING run.id, run.team_id, run.workflow_id, run.workflow_version_id, run.recipient_id, run.status, run.trigger_key, run.data, run.scheduled_at, run.started_at, run.completed_at, run.failed_at, run.canceled_at, run.error_code, run.error_message, run.created_at, run.updated_at
`

type ClaimNotificationRunsParams struct {
	LimitCount int32 `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ClaimNotificationRuns(ctx context.Context, arg ClaimNotificationRunsParams) ([]NotificationRun, error) {
	rows, err := q.db.Query(ctx, claimNotificationRuns, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRun{}
	for rows.Next() {
		var i NotificationRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.RecipientID,
			&i.Status,
			&i.TriggerKey,
			&i.Data,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CanceledAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationRun = `-- name: CreateNotificationRun :one
INSERT INTO notification_runs (
    team_id, workflow_id, workflow_version_id, recipient_id,
    status, trigger_key, data, scheduled_at
)
SELECT
    workflow.team_id,
    workflow.id,
    version.id,
    recipient.id,
    'queued',
    $1,
    $2,
    $3
FROM notification_workflows AS workflow
JOIN notification_workflow_versions AS version
  ON version.id = $4
 AND version.workflow_id = workflow.id
 AND version.team_id = workflow.team_id
JOIN notification_recipients AS recipient
  ON recipient.id = $5
 AND recipient.team_id = workflow.team_id
JOIN teams AS team ON team.id = workflow.team_id
WHERE workflow.id = $6
  AND workflow.team_id = $7
  AND workflow.enabled = true
  AND version.status = 'published'
  AND team.status = 'active'
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type CreateNotificationRunParams struct {
	TriggerKey        *string            `db:"trigger_key" json:"trigger_key"`
	Data              []byte             `db:"data" json:"data"`
	ScheduledAt       pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	WorkflowVersionID uuid.UUID          `db:"workflow_version_id" json:"workflow_version_id"`
	RecipientID       uuid.UUID          `db:"recipient_id" json:"recipient_id"`
	WorkflowID        uuid.UUID          `db:"workflow_id" json:"workflow_id"`
	TeamID            uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateNotificationRun(ctx context.Context, arg CreateNotificationRunParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, createNotificationRun,
		arg.TriggerKey,
		arg.Data,
		arg.ScheduledAt,
		arg.WorkflowVersionID,
		arg.RecipientID,
		arg.WorkflowID,
		arg.TeamID,
	)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationRun = `-- name: GetNotificationRun :one
SELECT run.id, run.team_id, run.workflow_id, run.workflow_version_id, run.recipient_id, run.status, run.trigger_key, run.data, run.scheduled_at, run.started_at, run.completed_at, run.failed_at, run.canceled_at, run.error_code, run.error_message, run.created_at, run.updated_at
FROM notification_runs AS run
JOIN teams AS team ON team.id = run.team_id
WHERE run.id = $1
  AND run.team_id = $2
  AND team.status = 'active'
`

type GetNotificationRunParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationRun(ctx context.Context, arg GetNotificationRunParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, getNotificationRun, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationRunForUpdate = `-- name: GetNotificationRunForUpdate :one
SELECT id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
FROM notification_runs
WHERE id = $1
  AND team_id = $2
FOR UPDATE
`

type GetNotificationRunForUpdateParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetNotificationRunForUpdate(ctx context.Context, arg GetNotificationRunForUpdateParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, getNotificationRunForUpdate, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationRuns = `-- name: ListNotificationRuns :many
SELECT run.id, run.team_id, run.workflow_id, run.workflow_version_id, run.recipient_id, run.status, run.trigger_key, run.data, run.scheduled_at, run.started_at, run.completed_at, run.failed_at, run.canceled_at, run.error_code, run.error_message, run.created_at, run.updated_at
FROM notification_runs AS run
JOIN teams AS team ON team.id = run.team_id
WHERE run.team_id = $1
  AND team.status = 'active'
ORDER BY run.created_at DESC, run.id DESC
LIMIT $3
OFFSET $2
`

type ListNotificationRunsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListNotificationRuns(ctx context.Context, arg ListNotificationRunsParams) ([]NotificationRun, error) {
	rows, err := q.db.Query(ctx, listNotificationRuns, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationRun{}
	for rows.Next() {
		var i NotificationRun
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.WorkflowID,
			&i.WorkflowVersionID,
			&i.RecipientID,
			&i.Status,
			&i.TriggerKey,
			&i.Data,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailedAt,
			&i.CanceledAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRunCompleted = `-- name: MarkNotificationRunCompleted :one
UPDATE notification_runs
SET status = 'completed',
    completed_at = now(),
    scheduled_at = NULL,
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('running', 'waiting')
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type MarkNotificationRunCompletedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationRunCompleted(ctx context.Context, arg MarkNotificationRunCompletedParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, markNotificationRunCompleted, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationRunFailed = `-- name: MarkNotificationRunFailed :one
UPDATE notification_runs
SET status = 'failed',
    failed_at = now(),
    scheduled_at = NULL,
    error_code = $1,
    error_message = $2,
    updated_at = now()
WHERE id = $3
  AND team_id = $4
  AND status IN ('queued', 'running', 'waiting')
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type MarkNotificationRunFailedParams struct {
	ErrorCode    *string   `db:"error_code" json:"error_code"`
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationRunFailed(ctx context.Context, arg MarkNotificationRunFailedParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, markNotificationRunFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.TeamID,
	)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationRunRunning = `-- name: MarkNotificationRunRunning :one
UPDATE notification_runs
SET status = 'running',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND status IN ('queued', 'waiting')
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type MarkNotificationRunRunningParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationRunRunning(ctx context.Context, arg MarkNotificationRunRunningParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, markNotificationRunRunning, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markNotificationRunWaiting = `-- name: MarkNotificationRunWaiting :one
UPDATE notification_runs
SET status = 'waiting',
    scheduled_at = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
  AND status = 'running'
RETURNING id, team_id, workflow_id, workflow_version_id, recipient_id, status, trigger_key, data, scheduled_at, started_at, completed_at, failed_at, canceled_at, error_code, error_message, created_at, updated_at
`

type MarkNotificationRunWaitingParams struct {
	ScheduledAt pgtype.Timestamptz `db:"scheduled_at" json:"scheduled_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkNotificationRunWaiting(ctx context.Context, arg MarkNotificationRunWaitingParams) (NotificationRun, error) {
	row := q.db.QueryRow(ctx, markNotificationRunWaiting, arg.ScheduledAt, arg.ID, arg.TeamID)
	var i NotificationRun
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.WorkflowID,
		&i.WorkflowVersionID,
		&i.RecipientID,
		&i.Status,
		&i.TriggerKey,
		&i.Data,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailedAt,
		&i.CanceledAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
