// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOIDCLoginState = `-- name: ConsumeOIDCLoginState :one
UPDATE oidc_login_states SET consumed_at=now()
WHERE state_hash=$1 AND consumed_at IS NULL AND expires_at > now()
RETURNING state_hash, connection_id, code_verifier_ciphertext, nonce, expires_at, consumed_at, created_at
`

type ConsumeOIDCLoginStateParams struct {
	StateHash string `db:"state_hash" json:"state_hash"`
}

func (q *Queries) ConsumeOIDCLoginState(ctx context.Context, arg ConsumeOIDCLoginStateParams) (OidcLoginState, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginState, arg.StateHash)
	var i OidcLoginState
	err := row.Scan(
		&i.StateHash,
		&i.ConnectionID,
		&i.CodeVerifierCiphertext,
		&i.Nonce,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOIDCLoginState = `-- name: CreateOIDCLoginState :exec
INSERT INTO oidc_login_states (state_hash, connection_id, code_verifier_ciphertext, nonce, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOIDCLoginStateParams struct {
	StateHash              string             `db:"state_hash" json:"state_hash"`
	ConnectionID           uuid.UUID          `db:"connection_id" json:"connection_id"`
	CodeVerifierCiphertext []byte             `db:"code_verifier_ciphertext" json:"code_verifier_ciphertext"`
	Nonce                  string             `db:"nonce" json:"nonce"`
	ExpiresAt              pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOIDCLoginState(ctx context.Context, arg CreateOIDCLoginStateParams) error {
	_, err := q.db.Exec(ctx, createOIDCLoginState,
		arg.StateHash,
		arg.ConnectionID,
		arg.CodeVerifierCiphertext,
		arg.Nonce,
		arg.ExpiresAt,
	)
	return err
}

const deleteOIDCConnection = `-- name: DeleteOIDCConnection :exec
DELETE FROM oidc_connections WHERE team_id=$1
`

type DeleteOIDCConnectionParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteOIDCConnection(ctx context.Context, arg DeleteOIDCConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteOIDCConnection, arg.TeamID)
	return err
}

const getOIDCConnection = `-- name: GetOIDCConnection :one
SELECT id, team_id, name, issuer_url, client_id, client_secret_ciphertext, allowed_domains, enabled, created_by, created_at, updated_at FROM oidc_connections WHERE id=$1 AND enabled
`

type GetOIDCConnectionParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetOIDCConnection(ctx context.Context, arg GetOIDCConnectionParams) (OidcConnection, error) {
	row := q.db.QueryRow(ctx, getOIDCConnection, arg.ID)
	var i OidcConnection
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AllowedDomains,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCConnectionByTeam = `-- name: GetOIDCConnectionByTeam :one
SELECT id, team_id, name, issuer_url, client_id, client_secret_ciphertext, allowed_domains, enabled, created_by, created_at, updated_at FROM oidc_connections WHERE team_id=$1
`

type GetOIDCConnectionByTeamParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetOIDCConnectionByTeam(ctx context.Context, arg GetOIDCConnectionByTeamParams) (OidcConnection, error) {
	row := q.db.QueryRow(ctx, getOIDCConnectionByTeam, arg.TeamID)
	var i OidcConnection
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AllowedDomains,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOIDCSecretsForRotation = `-- name: ListOIDCSecretsForRotation :many
SELECT id,client_secret_ciphertext FROM oidc_connections ORDER BY id
`

type ListOIDCSecretsForRotationRow struct {
	ID                     uuid.UUID `db:"id" json:"id"`
	ClientSecretCiphertext []byte    `db:"client_secret_ciphertext" json:"client_secret_ciphertext"`
}

func (q *Queries) ListOIDCSecretsForRotation(ctx context.Context) ([]ListOIDCSecretsForRotationRow, error) {
	rows, err := q.db.Query(ctx, listOIDCSecretsForRotation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOIDCSecretsForRotationRow{}
	for rows.Next() {
		var i ListOIDCSecretsForRotationRow
		if err := rows.Scan(&i.ID, &i.ClientSecretCiphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveOIDCIdentity = `-- name: ResolveOIDCIdentity :one
WITH existing_identity AS (
  SELECT user_id FROM external_identities WHERE external_identities.connection_id=$1 AND external_identities.subject=$2
), existing_user AS (
  SELECT users.id FROM users JOIN team_members ON team_members.user_id=users.id
  WHERE lower(users.email)=lower($3) AND team_members.team_id=$4 AND team_members.status='active'
), created_user AS (
  INSERT INTO users (email, email_verified, name)
  SELECT $3, true, $5
  WHERE NOT EXISTS (SELECT 1 FROM existing_identity) AND NOT EXISTS (SELECT 1 FROM existing_user)
  RETURNING id
), resolved AS (
  SELECT user_id AS id FROM existing_identity UNION ALL SELECT id FROM existing_user WHERE NOT EXISTS (SELECT 1 FROM existing_identity) UNION ALL SELECT id FROM created_user
), linked AS (
  INSERT INTO external_identities (user_id, connection_id, subject, email)
  SELECT id, $1, $2, $3 FROM resolved
  ON CONFLICT (connection_id, subject) DO UPDATE SET email=excluded.email, last_login_at=now()
  RETURNING user_id
), membership AS (
  INSERT INTO team_members (team_id, user_id, role, status)
  SELECT $4, user_id, 'member', 'active' FROM linked
  ON CONFLICT (team_id, user_id) DO NOTHING
)
SELECT users.id, users.email, users.email_verified, users.name, users.password_hash, users.created_at, users.updated_at, users.credential_version, users.security_updated_at FROM users JOIN linked ON linked.user_id=users.id
`

type ResolveOIDCIdentityParams struct {
	ConnectionID uuid.UUID `db:"connection_id" json:"connection_id"`
	Subject      string    `db:"subject" json:"subject"`
	Email        string    `db:"email" json:"email"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	Name         string    `db:"name" json:"name"`
}

func (q *Queries) ResolveOIDCIdentity(ctx context.Context, arg ResolveOIDCIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, resolveOIDCIdentity,
		arg.ConnectionID,
		arg.Subject,
		arg.Email,
		arg.TeamID,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.SecurityUpdatedAt,
	)
	return i, err
}

const rotateOIDCConnectionSecretCiphertext = `-- name: RotateOIDCConnectionSecretCiphertext :exec
UPDATE oidc_connections SET client_secret_ciphertext=$1,updated_at=now() WHERE id=$2 AND client_secret_ciphertext=$3
`

type RotateOIDCConnectionSecretCiphertextParams struct {
	NewCiphertext []byte    `db:"new_ciphertext" json:"new_ciphertext"`
	ID            uuid.UUID `db:"id" json:"id"`
	OldCiphertext []byte    `db:"old_ciphertext" json:"old_ciphertext"`
}

func (q *Queries) RotateOIDCConnectionSecretCiphertext(ctx context.Context, arg RotateOIDCConnectionSecretCiphertextParams) error {
	_, err := q.db.Exec(ctx, rotateOIDCConnectionSecretCiphertext, arg.NewCiphertext, arg.ID, arg.OldCiphertext)
	return err
}

const upsertOIDCConnection = `-- name: UpsertOIDCConnection :one
INSERT INTO oidc_connections (team_id, name, issuer_url, client_id, client_secret_ciphertext, allowed_domains, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (team_id) DO UPDATE SET name=excluded.name, issuer_url=excluded.issuer_url, client_id=excluded.client_id, client_secret_ciphertext=excluded.client_secret_ciphertext, allowed_domains=excluded.allowed_domains, enabled=excluded.enabled, updated_at=now()
RETURNING id, team_id, name, issuer_url, client_id, client_secret_ciphertext, allowed_domains, enabled, created_by, created_at, updated_at
`

type UpsertOIDCConnectionParams struct {
	TeamID                 uuid.UUID  `db:"team_id" json:"team_id"`
	Name                   string     `db:"name" json:"name"`
	IssuerUrl              string     `db:"issuer_url" json:"issuer_url"`
	ClientID               string     `db:"client_id" json:"client_id"`
	ClientSecretCiphertext []byte     `db:"client_secret_ciphertext" json:"client_secret_ciphertext"`
	AllowedDomains         []string   `db:"allowed_domains" json:"allowed_domains"`
	Enabled                bool       `db:"enabled" json:"enabled"`
	CreatedBy              *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) UpsertOIDCConnection(ctx context.Context, arg UpsertOIDCConnectionParams) (OidcConnection, error) {
	row := q.db.QueryRow(ctx, upsertOIDCConnection,
		arg.TeamID,
		arg.Name,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecretCiphertext,
		arg.AllowedDomains,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i OidcConnection
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecretCiphertext,
		&i.AllowedDomains,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
