// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) (TeamInvitation, error)
	ClaimSenderDomainsForReconciliation(ctx context.Context, arg ClaimSenderDomainsForReconciliationParams) ([]SenderDomain, error)
	ClaimWebhookDeliveries(ctx context.Context, arg ClaimWebhookDeliveriesParams) ([]ClaimWebhookDeliveriesRow, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CompleteSenderDomainHealthCheck(ctx context.Context, arg CompleteSenderDomainHealthCheckParams) (SenderDomain, error)
	CompleteSenderDomainReconciliation(ctx context.Context, arg CompleteSenderDomainReconciliationParams) (SenderDomain, error)
	ConfirmTOTPCredential(ctx context.Context, arg ConfirmTOTPCredentialParams) (int64, error)
	CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error
	CreateSMSMessage(ctx context.Context, arg CreateSMSMessageParams) (SmsMessage, error)
	CreateSenderDomain(ctx context.Context, arg CreateSenderDomainParams) (SenderDomain, error)
	CreateSenderID(ctx context.Context, arg CreateSenderIDParams) (SenderID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (TeamInvitation, error)
	CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error)
	CreateTeamToken(ctx context.Context, arg CreateTeamTokenParams) (TeamToken, error)
	CreateTeamWithOwner(ctx context.Context, arg CreateTeamWithOwnerParams) (CreateTeamWithOwnerRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error)
	CreateWebhookDeliveriesForEvent(ctx context.Context, arg CreateWebhookDeliveriesForEventParams) (int64, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error)
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	CreateWorkloadAccessToken(ctx context.Context, arg CreateWorkloadAccessTokenParams) (WorkloadAccessToken, error)
	CreateWorkloadCredential(ctx context.Context, arg CreateWorkloadCredentialParams) (WorkloadCredential, error)
	CreateWorkloadIdentity(ctx context.Context, arg CreateWorkloadIdentityParams) (WorkloadIdentity, error)
	DeclineTeamInvitation(ctx context.Context, arg DeclineTeamInvitationParams) (TeamInvitation, error)
	DeleteExpiredVerificationTokens(ctx context.Context) error
	DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error
	DeleteRecoveryCodes(ctx context.Context, arg DeleteRecoveryCodesParams) error
	DeleteSenderDomain(ctx context.Context, arg DeleteSenderDomainParams) (SenderDomain, error)
	DeleteSenderID(ctx context.Context, arg DeleteSenderIDParams) (SenderID, error)
	DeleteTOTPCredential(ctx context.Context, arg DeleteTOTPCredentialParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteVerificationToken(ctx context.Context, arg DeleteVerificationTokenParams) error
	DeleteVerificationTokensByIdentifier(ctx context.Context, arg DeleteVerificationTokensByIdentifierParams) error
	DisableTeam(ctx context.Context, arg DisableTeamParams) (Team, error)
	DisableWebhookEndpoint(ctx context.Context, arg DisableWebhookEndpointParams) (WebhookEndpoint, error)
	DisableWorkloadIdentity(ctx context.Context, arg DisableWorkloadIdentityParams) (WorkloadIdentity, error)
	DowngradeSessionAfterMFADisable(ctx context.Context, arg DowngradeSessionAfterMFADisableParams) error
	ElevateSessionAfterMFAEnrollment(ctx context.Context, arg ElevateSessionAfterMFAEnrollmentParams) (int64, error)
	FindApprovedSMSSender(ctx context.Context, arg FindApprovedSMSSenderParams) (uuid.UUID, error)
	GetActiveTeamTokenByHash(ctx context.Context, arg GetActiveTeamTokenByHashParams) (TeamToken, error)
	GetActiveWorkloadAccessTokenByHash(ctx context.Context, arg GetActiveWorkloadAccessTokenByHashParams) (GetActiveWorkloadAccessTokenByHashRow, error)
	GetActiveWorkloadCredentialByHash(ctx context.Context, arg GetActiveWorkloadCredentialByHashParams) (GetActiveWorkloadCredentialByHashRow, error)
	GetEmailMessage(ctx context.Context, arg GetEmailMessageParams) (EmailMessage, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error)
	GetSMSMessage(ctx context.Context, arg GetSMSMessageParams) (SmsMessage, error)
	GetSenderDomain(ctx context.Context, arg GetSenderDomainParams) (SenderDomain, error)
	GetSenderDomainByDomain(ctx context.Context, arg GetSenderDomainByDomainParams) (SenderDomain, error)
	GetSenderID(ctx context.Context, arg GetSenderIDParams) (SenderID, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error)
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	GetTOTPCredential(ctx context.Context, arg GetTOTPCredentialParams) (GetTOTPCredentialRow, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (Team, error)
	GetTeamIdentityPolicy(ctx context.Context, arg GetTeamIdentityPolicyParams) (GetTeamIdentityPolicyRow, error)
	GetTeamInvitationByTokenHash(ctx context.Context, arg GetTeamInvitationByTokenHashParams) (TeamInvitation, error)
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (VerificationToken, error)
	GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error)
	GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error)
	GetWebhookEvent(ctx context.Context, arg GetWebhookEventParams) (WebhookEvent, error)
	GetWorkloadIdentity(ctx context.Context, arg GetWorkloadIdentityParams) (WorkloadIdentity, error)
	IsTOTPEnabled(ctx context.Context, arg IsTOTPEnabledParams) (bool, error)
	ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]ListEmailMessagesRow, error)
	ListOAuthIdentitiesByUserID(ctx context.Context, arg ListOAuthIdentitiesByUserIDParams) ([]OauthIdentity, error)
	ListPendingTeamInvitations(ctx context.Context, arg ListPendingTeamInvitationsParams) ([]TeamInvitation, error)
	ListSMSMessages(ctx context.Context, arg ListSMSMessagesParams) ([]SmsMessage, error)
	ListSenderDomains(ctx context.Context, arg ListSenderDomainsParams) ([]SenderDomain, error)
	ListSenderIDs(ctx context.Context, arg ListSenderIDsParams) ([]SenderID, error)
	ListSessionsByUserID(ctx context.Context, arg ListSessionsByUserIDParams) ([]Session, error)
	ListSubscribedWebhookEndpoints(ctx context.Context, arg ListSubscribedWebhookEndpointsParams) ([]WebhookEndpoint, error)
	ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]TeamMember, error)
	ListTeamTokens(ctx context.Context, arg ListTeamTokensParams) ([]TeamToken, error)
	ListTeamsForUser(ctx context.Context, arg ListTeamsForUserParams) ([]Team, error)
	ListWebhookDeliveriesForEvent(ctx context.Context, arg ListWebhookDeliveriesForEventParams) ([]WebhookDelivery, error)
	ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error)
	ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error)
	ListWebhookEventsForObject(ctx context.Context, arg ListWebhookEventsForObjectParams) ([]WebhookEvent, error)
	ListWorkloadIdentities(ctx context.Context, arg ListWorkloadIdentitiesParams) ([]WorkloadIdentity, error)
	MarkSMSMessageDeliveryUnknown(ctx context.Context, arg MarkSMSMessageDeliveryUnknownParams) (SmsMessage, error)
	MarkSMSMessageFailed(ctx context.Context, arg MarkSMSMessageFailedParams) (SmsMessage, error)
	MarkSMSMessageProcessing(ctx context.Context, arg MarkSMSMessageProcessingParams) (SmsMessage, error)
	MarkSMSMessageSubmitted(ctx context.Context, arg MarkSMSMessageSubmittedParams) (SmsMessage, error)
	MarkUserEmailVerifiedByEmail(ctx context.Context, arg MarkUserEmailVerifiedByEmailParams) (User, error)
	MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (MarkWebhookDeliveryFailedRow, error)
	MarkWebhookDeliverySucceeded(ctx context.Context, arg MarkWebhookDeliverySucceededParams) (MarkWebhookDeliverySucceededRow, error)
	PutUnverifiedTOTPCredential(ctx context.Context, arg PutUnverifiedTOTPCredentialParams) (int64, error)
	RecordSenderDomainHealthFailure(ctx context.Context, arg RecordSenderDomainHealthFailureParams) (SenderDomain, error)
	RecordSenderDomainReconciliationFailure(ctx context.Context, arg RecordSenderDomainReconciliationFailureParams) (SenderDomain, error)
	ReleaseWebhookDeliveryClaim(ctx context.Context, arg ReleaseWebhookDeliveryClaimParams) (int64, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	ResetPasswordWithToken(ctx context.Context, arg ResetPasswordWithTokenParams) (ResetPasswordWithTokenRow, error)
	RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) (WebhookDelivery, error)
	RevokeOtherSessionsAfterMFADisable(ctx context.Context, arg RevokeOtherSessionsAfterMFADisableParams) error
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeTeamToken(ctx context.Context, arg RevokeTeamTokenParams) (TeamToken, error)
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error
	RevokeWorkloadCredential(ctx context.Context, arg RevokeWorkloadCredentialParams) (WorkloadCredential, error)
	RotateWebhookEndpointSecret(ctx context.Context, arg RotateWebhookEndpointSecretParams) (WebhookEndpoint, error)
	ScheduleWebhookDeliveryRetry(ctx context.Context, arg ScheduleWebhookDeliveryRetryParams) (WebhookDelivery, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchTeamToken(ctx context.Context, arg TouchTeamTokenParams) error
	TouchWorkloadAccessToken(ctx context.Context, arg TouchWorkloadAccessTokenParams) error
	TouchWorkloadCredential(ctx context.Context, arg TouchWorkloadCredentialParams) error
	UpdateSMSMessageStatus(ctx context.Context, arg UpdateSMSMessageStatusParams) (SmsMessage, error)
	UpdateSenderDomainVerification(ctx context.Context, arg UpdateSenderDomainVerificationParams) (SenderDomain, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error)
	UpdateTeamToken(ctx context.Context, arg UpdateTeamTokenParams) (TeamToken, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPasswordByEmail(ctx context.Context, arg UpdateUserPasswordByEmailParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error)
	UpdateWorkloadIdentity(ctx context.Context, arg UpdateWorkloadIdentityParams) (WorkloadIdentity, error)
	UpsertTeamIdentityPolicy(ctx context.Context, arg UpsertTeamIdentityPolicyParams) (TeamIdentityPolicy, error)
	UseRecoveryCodeAndElevateSession(ctx context.Context, arg UseRecoveryCodeAndElevateSessionParams) (int64, error)
	VerifyEmailWithToken(ctx context.Context, arg VerifyEmailWithTokenParams) (User, error)
	VerifyTOTPAndElevateSession(ctx context.Context, arg VerifyTOTPAndElevateSessionParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
