// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) (TeamInvitation, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateSenderID(ctx context.Context, arg CreateSenderIDParams) (SenderID, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (TeamInvitation, error)
	CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error)
	CreateTeamToken(ctx context.Context, arg CreateTeamTokenParams) (TeamToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error)
	DeclineTeamInvitation(ctx context.Context, arg DeclineTeamInvitationParams) (TeamInvitation, error)
	DeleteExpiredVerificationTokens(ctx context.Context) error
	DeleteSenderID(ctx context.Context, arg DeleteSenderIDParams) (SenderID, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteVerificationToken(ctx context.Context, arg DeleteVerificationTokenParams) error
	DeleteVerificationTokensByIdentifier(ctx context.Context, arg DeleteVerificationTokensByIdentifierParams) error
	DisableTeam(ctx context.Context, arg DisableTeamParams) (Team, error)
	GetActiveTeamTokenByHash(ctx context.Context, arg GetActiveTeamTokenByHashParams) (TeamToken, error)
	GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error)
	GetSenderID(ctx context.Context, arg GetSenderIDParams) (SenderID, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (Session, error)
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (Session, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (Team, error)
	GetTeamInvitationByTokenHash(ctx context.Context, arg GetTeamInvitationByTokenHashParams) (TeamInvitation, error)
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (VerificationToken, error)
	ListOAuthIdentitiesByUserID(ctx context.Context, arg ListOAuthIdentitiesByUserIDParams) ([]OauthIdentity, error)
	ListPendingTeamInvitations(ctx context.Context, arg ListPendingTeamInvitationsParams) ([]TeamInvitation, error)
	ListSenderIDs(ctx context.Context, arg ListSenderIDsParams) ([]SenderID, error)
	ListSessionsByUserID(ctx context.Context, arg ListSessionsByUserIDParams) ([]Session, error)
	ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]TeamMember, error)
	ListTeamTokens(ctx context.Context, arg ListTeamTokensParams) ([]TeamToken, error)
	ListTeamsForUser(ctx context.Context, arg ListTeamsForUserParams) ([]Team, error)
	MarkUserEmailVerifiedByEmail(ctx context.Context, arg MarkUserEmailVerifiedByEmailParams) (User, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeTeamToken(ctx context.Context, arg RevokeTeamTokenParams) (TeamToken, error)
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchTeamToken(ctx context.Context, arg TouchTeamTokenParams) error
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error)
	UpdateTeamToken(ctx context.Context, arg UpdateTeamTokenParams) (TeamToken, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPasswordByEmail(ctx context.Context, arg UpdateUserPasswordByEmailParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
