// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSCIMUsers = `-- name: CountSCIMUsers :one
SELECT count(*) FROM team_members JOIN users ON users.id=team_members.user_id WHERE team_members.team_id=$1 AND ($2::text IS NULL OR lower(users.email)=lower($2))
`

type CountSCIMUsersParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Email  *string   `db:"email" json:"email"`
}

func (q *Queries) CountSCIMUsers(ctx context.Context, arg CountSCIMUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMUsers, arg.TeamID, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSCIMToken = `-- name: CreateSCIMToken :one
INSERT INTO scim_tokens(team_id,name,token_hash,created_by,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING id, team_id, name, token_hash, created_by, last_used_at, expires_at, revoked_at, created_at
`

type CreateSCIMTokenParams struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	Name      string             `db:"name" json:"name"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	CreatedBy *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSCIMToken(ctx context.Context, arg CreateSCIMTokenParams) (ScimToken, error) {
	row := q.db.QueryRow(ctx, createSCIMToken,
		arg.TeamID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ScimToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deprovisionSCIMUser = `-- name: DeprovisionSCIMUser :exec
UPDATE team_members SET status='suspended',updated_at=now() WHERE team_id=$1 AND user_id=$2
`

type DeprovisionSCIMUserParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeprovisionSCIMUser(ctx context.Context, arg DeprovisionSCIMUserParams) error {
	_, err := q.db.Exec(ctx, deprovisionSCIMUser, arg.TeamID, arg.UserID)
	return err
}

const getActiveSCIMTokenByHash = `-- name: GetActiveSCIMTokenByHash :one
SELECT id, team_id, name, token_hash, created_by, last_used_at, expires_at, revoked_at, created_at FROM scim_tokens WHERE token_hash=$1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

type GetActiveSCIMTokenByHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetActiveSCIMTokenByHash(ctx context.Context, arg GetActiveSCIMTokenByHashParams) (ScimToken, error) {
	row := q.db.QueryRow(ctx, getActiveSCIMTokenByHash, arg.TokenHash)
	var i ScimToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSCIMUser = `-- name: GetSCIMUser :one
SELECT users.id, users.email, users.email_verified, users.name, users.password_hash, users.created_at, users.updated_at, users.credential_version, users.security_updated_at, team_members.status AS membership_status, scim_external_ids.external_id, COALESCE(NULLIF(scim_external_ids.display_name,''), users.name) AS scim_name
FROM team_members JOIN users ON users.id=team_members.user_id LEFT JOIN scim_external_ids ON scim_external_ids.team_id=team_members.team_id AND scim_external_ids.user_id=users.id
WHERE team_members.team_id=$1 AND users.id=$2
`

type GetSCIMUserParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetSCIMUserRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	Name              string             `db:"name" json:"name"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CredentialVersion int64              `db:"credential_version" json:"credential_version"`
	SecurityUpdatedAt pgtype.Timestamptz `db:"security_updated_at" json:"security_updated_at"`
	MembershipStatus  string             `db:"membership_status" json:"membership_status"`
	ExternalID        *string            `db:"external_id" json:"external_id"`
	ScimName          string             `db:"scim_name" json:"scim_name"`
}

func (q *Queries) GetSCIMUser(ctx context.Context, arg GetSCIMUserParams) (GetSCIMUserRow, error) {
	row := q.db.QueryRow(ctx, getSCIMUser, arg.TeamID, arg.UserID)
	var i GetSCIMUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.SecurityUpdatedAt,
		&i.MembershipStatus,
		&i.ExternalID,
		&i.ScimName,
	)
	return i, err
}

const listSCIMTokens = `-- name: ListSCIMTokens :many
SELECT id, team_id, name, token_hash, created_by, last_used_at, expires_at, revoked_at, created_at FROM scim_tokens WHERE team_id=$1 ORDER BY created_at DESC
`

type ListSCIMTokensParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListSCIMTokens(ctx context.Context, arg ListSCIMTokensParams) ([]ScimToken, error) {
	rows, err := q.db.Query(ctx, listSCIMTokens, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScimToken{}
	for rows.Next() {
		var i ScimToken
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT users.id, users.email, users.email_verified, users.name, users.password_hash, users.created_at, users.updated_at, users.credential_version, users.security_updated_at, team_members.status AS membership_status, scim_external_ids.external_id, COALESCE(NULLIF(scim_external_ids.display_name,''), users.name) AS scim_name
FROM team_members JOIN users ON users.id=team_members.user_id LEFT JOIN scim_external_ids ON scim_external_ids.team_id=team_members.team_id AND scim_external_ids.user_id=users.id
WHERE team_members.team_id=$1 AND ($2::text IS NULL OR lower(users.email)=lower($2))
ORDER BY users.created_at, users.id LIMIT $4 OFFSET $3
`

type ListSCIMUsersParams struct {
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	Email      *string   `db:"email" json:"email"`
	PageOffset int32     `db:"page_offset" json:"page_offset"`
	PageSize   int32     `db:"page_size" json:"page_size"`
}

type ListSCIMUsersRow struct {
	ID                uuid.UUID          `db:"id" json:"id"`
	Email             string             `db:"email" json:"email"`
	EmailVerified     bool               `db:"email_verified" json:"email_verified"`
	Name              string             `db:"name" json:"name"`
	PasswordHash      *string            `db:"password_hash" json:"password_hash"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CredentialVersion int64              `db:"credential_version" json:"credential_version"`
	SecurityUpdatedAt pgtype.Timestamptz `db:"security_updated_at" json:"security_updated_at"`
	MembershipStatus  string             `db:"membership_status" json:"membership_status"`
	ExternalID        *string            `db:"external_id" json:"external_id"`
	ScimName          string             `db:"scim_name" json:"scim_name"`
}

func (q *Queries) ListSCIMUsers(ctx context.Context, arg ListSCIMUsersParams) ([]ListSCIMUsersRow, error) {
	rows, err := q.db.Query(ctx, listSCIMUsers,
		arg.TeamID,
		arg.Email,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSCIMUsersRow{}
	for rows.Next() {
		var i ListSCIMUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CredentialVersion,
			&i.SecurityUpdatedAt,
			&i.MembershipStatus,
			&i.ExternalID,
			&i.ScimName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const provisionSCIMUser = `-- name: ProvisionSCIMUser :one
WITH existing AS (
 SELECT users.id FROM users JOIN team_members ON team_members.user_id=users.id WHERE lower(users.email)=lower($1) AND team_members.team_id=$2
), created AS (
 INSERT INTO users(email,email_verified,name) SELECT $1,true,$3 WHERE NOT EXISTS(SELECT 1 FROM existing) RETURNING id
), resolved AS (SELECT id FROM existing UNION ALL SELECT id FROM created), membership AS (
 INSERT INTO team_members(team_id,user_id,role,status) SELECT $2,id,'member','active' FROM resolved ON CONFLICT(team_id,user_id) DO UPDATE SET status='active',updated_at=now() RETURNING user_id
), mapping AS (
 INSERT INTO scim_external_ids(team_id,user_id,external_id,display_name) SELECT $2,membership.user_id,$4,$3 FROM membership
 ON CONFLICT(team_id,user_id) DO UPDATE SET external_id=excluded.external_id,display_name=excluded.display_name,updated_at=now() RETURNING user_id
)
SELECT users.id, users.email, users.email_verified, users.name, users.password_hash, users.created_at, users.updated_at, users.credential_version, users.security_updated_at FROM users JOIN mapping ON mapping.user_id=users.id
`

type ProvisionSCIMUserParams struct {
	Email      string    `db:"email" json:"email"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
	Name       string    `db:"name" json:"name"`
	ExternalID string    `db:"external_id" json:"external_id"`
}

func (q *Queries) ProvisionSCIMUser(ctx context.Context, arg ProvisionSCIMUserParams) (User, error) {
	row := q.db.QueryRow(ctx, provisionSCIMUser,
		arg.Email,
		arg.TeamID,
		arg.Name,
		arg.ExternalID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CredentialVersion,
		&i.SecurityUpdatedAt,
	)
	return i, err
}

const revokeSCIMToken = `-- name: RevokeSCIMToken :exec
UPDATE scim_tokens SET revoked_at=now() WHERE id=$1 AND team_id=$2 AND revoked_at IS NULL
`

type RevokeSCIMTokenParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RevokeSCIMToken(ctx context.Context, arg RevokeSCIMTokenParams) error {
	_, err := q.db.Exec(ctx, revokeSCIMToken, arg.ID, arg.TeamID)
	return err
}

const touchSCIMToken = `-- name: TouchSCIMToken :exec
UPDATE scim_tokens SET last_used_at=now() WHERE id=$1 AND (last_used_at IS NULL OR last_used_at < now()-interval '5 minutes')
`

type TouchSCIMTokenParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchSCIMToken(ctx context.Context, arg TouchSCIMTokenParams) error {
	_, err := q.db.Exec(ctx, touchSCIMToken, arg.ID)
	return err
}

const updateSCIMUser = `-- name: UpdateSCIMUser :exec
WITH member AS (UPDATE team_members SET status=$3,updated_at=now() WHERE team_id=$2 AND team_members.user_id=$4 RETURNING team_members.user_id)
UPDATE scim_external_ids SET display_name=$1,updated_at=now() FROM member WHERE scim_external_ids.team_id=$2 AND scim_external_ids.user_id=member.user_id
`

type UpdateSCIMUserParams struct {
	Name   string    `db:"name" json:"name"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Status string    `db:"status" json:"status"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateSCIMUser(ctx context.Context, arg UpdateSCIMUserParams) error {
	_, err := q.db.Exec(ctx, updateSCIMUser,
		arg.Name,
		arg.TeamID,
		arg.Status,
		arg.UserID,
	)
	return err
}
