// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sender_domains.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSenderDomain = `-- name: CreateSenderDomain :one
INSERT INTO sender_domains (
    team_id,
    domain,
    provider,
    provider_region,
    verification_records,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type CreateSenderDomainParams struct {
	TeamID              uuid.UUID  `db:"team_id" json:"team_id"`
	Domain              string     `db:"domain" json:"domain"`
	Provider            string     `db:"provider" json:"provider"`
	ProviderRegion      string     `db:"provider_region" json:"provider_region"`
	VerificationRecords []byte     `db:"verification_records" json:"verification_records"`
	CreatedBy           *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateSenderDomain(ctx context.Context, arg CreateSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, createSenderDomain,
		arg.TeamID,
		arg.Domain,
		arg.Provider,
		arg.ProviderRegion,
		arg.VerificationRecords,
		arg.CreatedBy,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSenderDomain = `-- name: DeleteSenderDomain :one
DELETE FROM sender_domains
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type DeleteSenderDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteSenderDomain(ctx context.Context, arg DeleteSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, deleteSenderDomain, arg.ID, arg.TeamID)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSenderDomain = `-- name: GetSenderDomain :one
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE id = $1
  AND team_id = $2
`

type GetSenderDomainParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSenderDomain(ctx context.Context, arg GetSenderDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, getSenderDomain, arg.ID, arg.TeamID)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSenderDomainByDomain = `-- name: GetSenderDomainByDomain :one
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE team_id = $1
  AND domain = $2
`

type GetSenderDomainByDomainParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Domain string    `db:"domain" json:"domain"`
}

func (q *Queries) GetSenderDomainByDomain(ctx context.Context, arg GetSenderDomainByDomainParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, getSenderDomainByDomain, arg.TeamID, arg.Domain)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSenderDomains = `-- name: ListSenderDomains :many
SELECT id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
FROM sender_domains
WHERE team_id = $1
ORDER BY created_at DESC
`

type ListSenderDomainsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListSenderDomains(ctx context.Context, arg ListSenderDomainsParams) ([]SenderDomain, error) {
	rows, err := q.db.Query(ctx, listSenderDomains, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SenderDomain{}
	for rows.Next() {
		var i SenderDomain
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Domain,
			&i.Provider,
			&i.ProviderRegion,
			&i.Status,
			&i.VerificationRecords,
			&i.FailureReason,
			&i.LastCheckedAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSenderDomainVerification = `-- name: UpdateSenderDomainVerification :one
UPDATE sender_domains
SET status = $1,
    verification_records = $2,
    failure_reason = $3,
    last_checked_at = now(),
    verified_at = CASE WHEN $1 = 'verified' THEN now() ELSE verified_at END,
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, team_id, domain, provider, provider_region, status, verification_records, failure_reason, last_checked_at, verified_at, disabled_at, created_by, created_at, updated_at
`

type UpdateSenderDomainVerificationParams struct {
	Status              string    `db:"status" json:"status"`
	VerificationRecords []byte    `db:"verification_records" json:"verification_records"`
	FailureReason       *string   `db:"failure_reason" json:"failure_reason"`
	ID                  uuid.UUID `db:"id" json:"id"`
	TeamID              uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateSenderDomainVerification(ctx context.Context, arg UpdateSenderDomainVerificationParams) (SenderDomain, error) {
	row := q.db.QueryRow(ctx, updateSenderDomainVerification,
		arg.Status,
		arg.VerificationRecords,
		arg.FailureReason,
		arg.ID,
		arg.TeamID,
	)
	var i SenderDomain
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Domain,
		&i.Provider,
		&i.ProviderRegion,
		&i.Status,
		&i.VerificationRecords,
		&i.FailureReason,
		&i.LastCheckedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
