// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sms_messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createSMSMessage = `-- name: CreateSMSMessage :one
INSERT INTO sms_messages (
    team_id,
    sender_id,
    to_number,
    from_name,
    body,
    status,
    segments,
    cost_micros,
    client_reference,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (team_id, client_reference) WHERE client_reference IS NOT NULL
DO UPDATE SET updated_at = sms_messages.updated_at
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
`

type CreateSMSMessageParams struct {
	TeamID          uuid.UUID  `db:"team_id" json:"team_id"`
	SenderID        *uuid.UUID `db:"sender_id" json:"sender_id"`
	ToNumber        string     `db:"to_number" json:"to_number"`
	FromName        string     `db:"from_name" json:"from_name"`
	Body            string     `db:"body" json:"body"`
	Status          string     `db:"status" json:"status"`
	Segments        int32      `db:"segments" json:"segments"`
	CostMicros      int64      `db:"cost_micros" json:"cost_micros"`
	ClientReference *string    `db:"client_reference" json:"client_reference"`
	Metadata        []byte     `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateSMSMessage(ctx context.Context, arg CreateSMSMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, createSMSMessage,
		arg.TeamID,
		arg.SenderID,
		arg.ToNumber,
		arg.FromName,
		arg.Body,
		arg.Status,
		arg.Segments,
		arg.CostMicros,
		arg.ClientReference,
		arg.Metadata,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.CostMicros,
		&i.ClientReference,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findApprovedSMSSender = `-- name: FindApprovedSMSSender :one
SELECT id
FROM sender_ids
WHERE team_id = $1
  AND lower(name) = lower($2)
  AND status = 'approved'
ORDER BY created_at DESC
LIMIT 1
`

type FindApprovedSMSSenderParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) FindApprovedSMSSender(ctx context.Context, arg FindApprovedSMSSenderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findApprovedSMSSender, arg.TeamID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSMSMessage = `-- name: GetSMSMessage :one
SELECT id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
FROM sms_messages
WHERE id = $1
  AND team_id = $2
`

type GetSMSMessageParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetSMSMessage(ctx context.Context, arg GetSMSMessageParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, getSMSMessage, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.CostMicros,
		&i.ClientReference,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSMSMessages = `-- name: ListSMSMessages :many
SELECT id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
FROM sms_messages
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListSMSMessagesParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListSMSMessages(ctx context.Context, arg ListSMSMessagesParams) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listSMSMessages, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.SenderID,
			&i.ToNumber,
			&i.FromName,
			&i.Body,
			&i.Status,
			&i.ProviderID,
			&i.ProviderMessageID,
			&i.Segments,
			&i.CostMicros,
			&i.ClientReference,
			&i.ErrorMessage,
			&i.Metadata,
			&i.SubmittedAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSMSMessageFailed = `-- name: MarkSMSMessageFailed :one
UPDATE sms_messages
SET status = 'failed',
    error_message = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
`

type MarkSMSMessageFailedParams struct {
	ErrorMessage *string   `db:"error_message" json:"error_message"`
	ID           uuid.UUID `db:"id" json:"id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageFailed(ctx context.Context, arg MarkSMSMessageFailedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageFailed, arg.ErrorMessage, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.CostMicros,
		&i.ClientReference,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markSMSMessageSubmitted = `-- name: MarkSMSMessageSubmitted :one
UPDATE sms_messages
SET provider_id = $1,
    provider_message_id = $2,
    status = $3,
    error_message = NULL,
    submitted_at = COALESCE(submitted_at, now()),
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
`

type MarkSMSMessageSubmittedParams struct {
	ProviderID        *string   `db:"provider_id" json:"provider_id"`
	ProviderMessageID *string   `db:"provider_message_id" json:"provider_message_id"`
	Status            string    `db:"status" json:"status"`
	ID                uuid.UUID `db:"id" json:"id"`
	TeamID            uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) MarkSMSMessageSubmitted(ctx context.Context, arg MarkSMSMessageSubmittedParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, markSMSMessageSubmitted,
		arg.ProviderID,
		arg.ProviderMessageID,
		arg.Status,
		arg.ID,
		arg.TeamID,
	)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.CostMicros,
		&i.ClientReference,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSMSMessageStatus = `-- name: UpdateSMSMessageStatus :one
UPDATE sms_messages
SET status = $1,
    delivered_at = CASE
        WHEN $1 = 'delivered'
            THEN COALESCE(delivered_at, now())
        ELSE delivered_at
    END,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
RETURNING id, team_id, sender_id, to_number, from_name, body, status, provider_id, provider_message_id, segments, cost_micros, client_reference, error_message, metadata, submitted_at, delivered_at, created_at, updated_at
`

type UpdateSMSMessageStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateSMSMessageStatus(ctx context.Context, arg UpdateSMSMessageStatusParams) (SmsMessage, error) {
	row := q.db.QueryRow(ctx, updateSMSMessageStatus, arg.Status, arg.ID, arg.TeamID)
	var i SmsMessage
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.SenderID,
		&i.ToNumber,
		&i.FromName,
		&i.Body,
		&i.Status,
		&i.ProviderID,
		&i.ProviderMessageID,
		&i.Segments,
		&i.CostMicros,
		&i.ClientReference,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SubmittedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
