// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTeamInvitation = `-- name: AcceptTeamInvitation :one
UPDATE team_invitations
SET status = 'accepted',
    accepted_at = now(),
    updated_at = now()
WHERE token_hash = $1
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, team_id, email, role, status, token_hash, invited_by, expires_at, accepted_at, declined_at, created_at, updated_at
`

type AcceptTeamInvitationParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, acceptTeamInvitation, arg.TokenHash)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamInvitation = `-- name: CreateTeamInvitation :one
INSERT INTO team_invitations (
    team_id,
    email,
    role,
    token_hash,
    invited_by,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, team_id, email, role, status, token_hash, invited_by, expires_at, accepted_at, declined_at, created_at, updated_at
`

type CreateTeamInvitationParams struct {
	TeamID    uuid.UUID          `db:"team_id" json:"team_id"`
	Email     string             `db:"email" json:"email"`
	Role      string             `db:"role" json:"role"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	InvitedBy *uuid.UUID         `db:"invited_by" json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, createTeamInvitation,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declineTeamInvitation = `-- name: DeclineTeamInvitation :one
UPDATE team_invitations
SET status = 'declined',
    declined_at = now(),
    updated_at = now()
WHERE token_hash = $1
  AND status = 'pending'
  AND expires_at > now()
RETURNING id, team_id, email, role, status, token_hash, invited_by, expires_at, accepted_at, declined_at, created_at, updated_at
`

type DeclineTeamInvitationParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) DeclineTeamInvitation(ctx context.Context, arg DeclineTeamInvitationParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, declineTeamInvitation, arg.TokenHash)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamInvitationByTokenHash = `-- name: GetTeamInvitationByTokenHash :one
SELECT id, team_id, email, role, status, token_hash, invited_by, expires_at, accepted_at, declined_at, created_at, updated_at
FROM team_invitations
WHERE token_hash = $1
  AND status = 'pending'
  AND expires_at > now()
`

type GetTeamInvitationByTokenHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetTeamInvitationByTokenHash(ctx context.Context, arg GetTeamInvitationByTokenHashParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, getTeamInvitationByTokenHash, arg.TokenHash)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.DeclinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTeamInvitations = `-- name: ListPendingTeamInvitations :many
SELECT id, team_id, email, role, status, token_hash, invited_by, expires_at, accepted_at, declined_at, created_at, updated_at
FROM team_invitations
WHERE team_id = $1
  AND status = 'pending'
  AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingTeamInvitationsParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListPendingTeamInvitations(ctx context.Context, arg ListPendingTeamInvitationsParams) ([]TeamInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingTeamInvitations, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamInvitation{}
	for rows.Next() {
		var i TeamInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.DeclinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
