// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTeamToken = `-- name: CreateTeamToken :one
INSERT INTO team_tokens (
    team_id,
    name,
    token_hash,
    token_prefix,
    permissions,
    created_by,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type CreateTeamTokenParams struct {
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
	Name        string             `db:"name" json:"name"`
	TokenHash   string             `db:"token_hash" json:"token_hash"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	Permissions []string           `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID         `db:"created_by" json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateTeamToken(ctx context.Context, arg CreateTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, createTeamToken,
		arg.TeamID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Permissions,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamTokenByHash = `-- name: GetActiveTeamTokenByHash :one
SELECT id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM team_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type GetActiveTeamTokenByHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetActiveTeamTokenByHash(ctx context.Context, arg GetActiveTeamTokenByHashParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, getActiveTeamTokenByHash, arg.TokenHash)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamTokens = `-- name: ListTeamTokens :many
SELECT id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
FROM team_tokens
WHERE team_id = $1
ORDER BY created_at DESC
`

type ListTeamTokensParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListTeamTokens(ctx context.Context, arg ListTeamTokensParams) ([]TeamToken, error) {
	rows, err := q.db.Query(ctx, listTeamTokens, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamToken{}
	for rows.Next() {
		var i TeamToken
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Permissions,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTeamToken = `-- name: RevokeTeamToken :one
UPDATE team_tokens
SET revoked_at = now(),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
  AND revoked_at IS NULL
RETURNING id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type RevokeTeamTokenParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RevokeTeamToken(ctx context.Context, arg RevokeTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, revokeTeamToken, arg.ID, arg.TeamID)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchTeamToken = `-- name: TouchTeamToken :exec
UPDATE team_tokens
SET last_used_at = now()
WHERE id = $1
`

type TouchTeamTokenParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchTeamToken(ctx context.Context, arg TouchTeamTokenParams) error {
	_, err := q.db.Exec(ctx, touchTeamToken, arg.ID)
	return err
}

const updateTeamToken = `-- name: UpdateTeamToken :one
UPDATE team_tokens
SET name = $1,
    permissions = $2,
    expires_at = $3,
    updated_at = now()
WHERE id = $4
  AND team_id = $5
  AND revoked_at IS NULL
RETURNING id, team_id, name, token_hash, token_prefix, permissions, created_by, expires_at, revoked_at, last_used_at, created_at, updated_at
`

type UpdateTeamTokenParams struct {
	Name        string             `db:"name" json:"name"`
	Permissions []string           `db:"permissions" json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ID          uuid.UUID          `db:"id" json:"id"`
	TeamID      uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateTeamToken(ctx context.Context, arg UpdateTeamTokenParams) (TeamToken, error) {
	row := q.db.QueryRow(ctx, updateTeamToken,
		arg.Name,
		arg.Permissions,
		arg.ExpiresAt,
		arg.ID,
		arg.TeamID,
	)
	var i TeamToken
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Permissions,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
