// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
    name,
    created_by
) VALUES (
    $1,
    $2
)
RETURNING id, name, status, created_by, created_at, updated_at
`

type CreateTeamParams struct {
	Name      string     `db:"name" json:"name"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.CreatedBy)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (
    team_id,
    user_id,
    role,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING team_id, user_id, role, status, created_at, updated_at
`

type CreateTeamMemberParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Role   string    `db:"role" json:"role"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableTeam = `-- name: DisableTeam :one
UPDATE teams
SET status = 'disabled',
    updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_by, created_at, updated_at
`

type DisableTeamParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DisableTeam(ctx context.Context, arg DisableTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, disableTeam, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, status, created_by, created_at, updated_at
FROM teams
WHERE id = $1
`

type GetTeamParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, role, status, created_at, updated_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT team_id, user_id, role, status, created_at, updated_at
FROM team_members
WHERE team_id = $1
ORDER BY created_at ASC
`

type ListTeamMembersParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]TeamMember, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.name, t.status, t.created_by, t.created_at, t.updated_at
FROM teams t
JOIN team_members tm ON tm.team_id = t.id
WHERE tm.user_id = $1
  AND tm.status = 'active'
  AND t.status = 'active'
ORDER BY t.created_at DESC
`

type ListTeamsForUserParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) ListTeamsForUser(ctx context.Context, arg ListTeamsForUserParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, name, status, created_by, created_at, updated_at
`

type UpdateTeamParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.Name, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE team_members
SET role = $1,
    updated_at = now()
WHERE team_id = $2
  AND user_id = $3
RETURNING team_id, user_id, role, status, created_at, updated_at
`

type UpdateTeamMemberRoleParams struct {
	Role   string    `db:"role" json:"role"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.Role, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
