// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (
    identifier,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING identifier, token_hash, expires_at, created_at
`

type CreateVerificationTokenParams struct {
	Identifier string             `db:"identifier" json:"identifier"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.Identifier, arg.TokenHash, arg.ExpiresAt)
	var i VerificationToken
	err := row.Scan(
		&i.Identifier,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredVerificationTokens = `-- name: DeleteExpiredVerificationTokens :exec
DELETE FROM verification_tokens
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerificationTokens)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM verification_tokens
WHERE identifier = $1
  AND token_hash = $2
`

type DeleteVerificationTokenParams struct {
	Identifier string `db:"identifier" json:"identifier"`
	TokenHash  string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) DeleteVerificationToken(ctx context.Context, arg DeleteVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, arg.Identifier, arg.TokenHash)
	return err
}

const deleteVerificationTokensByIdentifier = `-- name: DeleteVerificationTokensByIdentifier :exec
DELETE FROM verification_tokens
WHERE identifier = $1
`

type DeleteVerificationTokensByIdentifierParams struct {
	Identifier string `db:"identifier" json:"identifier"`
}

func (q *Queries) DeleteVerificationTokensByIdentifier(ctx context.Context, arg DeleteVerificationTokensByIdentifierParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensByIdentifier, arg.Identifier)
	return err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT identifier, token_hash, expires_at, created_at
FROM verification_tokens
WHERE identifier = $1
  AND token_hash = $2
  AND expires_at > now()
`

type GetVerificationTokenParams struct {
	Identifier string `db:"identifier" json:"identifier"`
	TokenHash  string `db:"token_hash" json:"token_hash"`
}

func (q *Queries) GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, arg.Identifier, arg.TokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.Identifier,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
