// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    team_id,
    currency
) VALUES (
    $1,
    $2
)
ON CONFLICT (team_id, currency) DO UPDATE
SET updated_at = wallets.updated_at
RETURNING id, team_id, currency, balance, status, created_at, updated_at
`

type CreateWalletParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Currency string    `db:"currency" json:"currency"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, arg.TeamID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transactions (
    wallet_id,
    team_id,
    transaction_type,
    reference_id,
    amount,
    balance_after,
    status,
    description,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, wallet_id, team_id, transaction_type, reference_id, amount, balance_after, status, description, metadata, created_at
`

type CreateWalletTransactionParams struct {
	WalletID        uuid.UUID  `db:"wallet_id" json:"wallet_id"`
	TeamID          uuid.UUID  `db:"team_id" json:"team_id"`
	TransactionType string     `db:"transaction_type" json:"transaction_type"`
	ReferenceID     *uuid.UUID `db:"reference_id" json:"reference_id"`
	Amount          int64      `db:"amount" json:"amount"`
	BalanceAfter    int64      `db:"balance_after" json:"balance_after"`
	Status          string     `db:"status" json:"status"`
	Description     *string    `db:"description" json:"description"`
	Metadata        []byte     `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, createWalletTransaction,
		arg.WalletID,
		arg.TeamID,
		arg.TransactionType,
		arg.ReferenceID,
		arg.Amount,
		arg.BalanceAfter,
		arg.Status,
		arg.Description,
		arg.Metadata,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TeamID,
		&i.TransactionType,
		&i.ReferenceID,
		&i.Amount,
		&i.BalanceAfter,
		&i.Status,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const creditWallet = `-- name: CreditWallet :one
UPDATE wallets
SET balance = balance + $1,
    updated_at = now()
WHERE id = $2
  AND status = 'active'
  AND $1 > 0
RETURNING id, team_id, currency, balance, status, created_at, updated_at
`

type CreditWalletParams struct {
	Amount int64     `db:"amount" json:"amount"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, creditWallet, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const debitWallet = `-- name: DebitWallet :one
UPDATE wallets
SET balance = balance - $1,
    updated_at = now()
WHERE id = $2
  AND status = 'active'
  AND $1 > 0
  AND balance >= $1
RETURNING id, team_id, currency, balance, status, created_at, updated_at
`

type DebitWalletParams struct {
	Amount int64     `db:"amount" json:"amount"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) DebitWallet(ctx context.Context, arg DebitWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, debitWallet, arg.Amount, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, team_id, currency, balance, status, created_at, updated_at
FROM wallets
WHERE id = $1
`

type GetWalletParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByTeamAndCurrency = `-- name: GetWalletByTeamAndCurrency :one
SELECT id, team_id, currency, balance, status, created_at, updated_at
FROM wallets
WHERE team_id = $1
  AND currency = $2
`

type GetWalletByTeamAndCurrencyParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Currency string    `db:"currency" json:"currency"`
}

func (q *Queries) GetWalletByTeamAndCurrency(ctx context.Context, arg GetWalletByTeamAndCurrencyParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByTeamAndCurrency, arg.TeamID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByTeamAndCurrencyForUpdate = `-- name: GetWalletByTeamAndCurrencyForUpdate :one
SELECT id, team_id, currency, balance, status, created_at, updated_at
FROM wallets
WHERE team_id = $1
  AND currency = $2
FOR UPDATE
`

type GetWalletByTeamAndCurrencyForUpdateParams struct {
	TeamID   uuid.UUID `db:"team_id" json:"team_id"`
	Currency string    `db:"currency" json:"currency"`
}

func (q *Queries) GetWalletByTeamAndCurrencyForUpdate(ctx context.Context, arg GetWalletByTeamAndCurrencyForUpdateParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByTeamAndCurrencyForUpdate, arg.TeamID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTransaction = `-- name: GetWalletTransaction :one
SELECT id, wallet_id, team_id, transaction_type, reference_id, amount, balance_after, status, description, metadata, created_at
FROM wallet_transactions
WHERE id = $1
  AND team_id = $2
`

type GetWalletTransactionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWalletTransaction(ctx context.Context, arg GetWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRow(ctx, getWalletTransaction, arg.ID, arg.TeamID)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.TeamID,
		&i.TransactionType,
		&i.ReferenceID,
		&i.Amount,
		&i.BalanceAfter,
		&i.Status,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamWalletTransactions = `-- name: ListTeamWalletTransactions :many
SELECT id, wallet_id, team_id, transaction_type, reference_id, amount, balance_after, status, description, metadata, created_at
FROM wallet_transactions
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListTeamWalletTransactionsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListTeamWalletTransactions(ctx context.Context, arg ListTeamWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listTeamWalletTransactions, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TeamID,
			&i.TransactionType,
			&i.ReferenceID,
			&i.Amount,
			&i.BalanceAfter,
			&i.Status,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT id, wallet_id, team_id, transaction_type, reference_id, amount, balance_after, status, description, metadata, created_at
FROM wallet_transactions
WHERE team_id = $1
  AND wallet_id = $2
ORDER BY created_at DESC
LIMIT $4
OFFSET $3
`

type ListWalletTransactionsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	WalletID    uuid.UUID `db:"wallet_id" json:"wallet_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]WalletTransaction, error) {
	rows, err := q.db.Query(ctx, listWalletTransactions,
		arg.TeamID,
		arg.WalletID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletTransaction{}
	for rows.Next() {
		var i WalletTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TeamID,
			&i.TransactionType,
			&i.ReferenceID,
			&i.Amount,
			&i.BalanceAfter,
			&i.Status,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletStatus = `-- name: UpdateWalletStatus :one
UPDATE wallets
SET status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, team_id, currency, balance, status, created_at, updated_at
`

type UpdateWalletStatusParams struct {
	Status string    `db:"status" json:"status"`
	ID     uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletStatus, arg.Status, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Currency,
		&i.Balance,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
