// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (
    id,
    team_id,
    event_type,
    object_type,
    object_id,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (id) DO UPDATE
SET id = EXCLUDED.id
RETURNING id, team_id, event_type, object_type, object_id, payload, occurred_at, created_at
`

type CreateWebhookEventParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TeamID     uuid.UUID          `db:"team_id" json:"team_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	ObjectType string             `db:"object_type" json:"object_type"`
	ObjectID   *uuid.UUID         `db:"object_id" json:"object_id"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.ID,
		arg.TeamID,
		arg.EventType,
		arg.ObjectType,
		arg.ObjectID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.EventType,
		&i.ObjectType,
		&i.ObjectID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, team_id, event_type, object_type, object_id, payload, occurred_at, created_at
FROM webhook_events
WHERE id = $1
  AND team_id = $2
`

type GetWebhookEventParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWebhookEvent(ctx context.Context, arg GetWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEvent, arg.ID, arg.TeamID)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.EventType,
		&i.ObjectType,
		&i.ObjectID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookEvents = `-- name: ListWebhookEvents :many
SELECT id, team_id, event_type, object_type, object_id, payload, occurred_at, created_at
FROM webhook_events
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListWebhookEventsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWebhookEvents(ctx context.Context, arg ListWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEvents, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.EventType,
			&i.ObjectType,
			&i.ObjectID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsForObject = `-- name: ListWebhookEventsForObject :many
SELECT id, team_id, event_type, object_type, object_id, payload, occurred_at, created_at
FROM webhook_events
WHERE team_id = $1
  AND object_type = $2
  AND object_id IS NOT DISTINCT FROM $3
ORDER BY occurred_at DESC, created_at DESC
LIMIT $5
OFFSET $4
`

type ListWebhookEventsForObjectParams struct {
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
	ObjectType  string     `db:"object_type" json:"object_type"`
	ObjectID    *uuid.UUID `db:"object_id" json:"object_id"`
	OffsetCount int32      `db:"offset_count" json:"offset_count"`
	LimitCount  int32      `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWebhookEventsForObject(ctx context.Context, arg ListWebhookEventsForObjectParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsForObject,
		arg.TeamID,
		arg.ObjectType,
		arg.ObjectID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.EventType,
			&i.ObjectType,
			&i.ObjectID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
