// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_endpoints.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (
    team_id,
    url,
    signing_secret,
    enabled,
    subscribed_events
) VALUES (
    $1,
    $2,
    $3,
    true,
    $4
)
RETURNING id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
`

type CreateWebhookEndpointParams struct {
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
	Url              string    `db:"url" json:"url"`
	SigningSecret    []byte    `db:"signing_secret" json:"signing_secret"`
	SubscribedEvents []string  `db:"subscribed_events" json:"subscribed_events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.TeamID,
		arg.Url,
		arg.SigningSecret,
		arg.SubscribedEvents,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Url,
		&i.SigningSecret,
		&i.Enabled,
		&i.SubscribedEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableWebhookEndpoint = `-- name: DisableWebhookEndpoint :one
UPDATE webhook_endpoints
SET enabled = false,
    disabled_at = COALESCE(disabled_at, now()),
    updated_at = now()
WHERE id = $1
  AND team_id = $2
RETURNING id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
`

type DisableWebhookEndpointParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DisableWebhookEndpoint(ctx context.Context, arg DisableWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, disableWebhookEndpoint, arg.ID, arg.TeamID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Url,
		&i.SigningSecret,
		&i.Enabled,
		&i.SubscribedEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
FROM webhook_endpoints
WHERE id = $1
  AND team_id = $2
`

type GetWebhookEndpointParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.ID, arg.TeamID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Url,
		&i.SigningSecret,
		&i.Enabled,
		&i.SubscribedEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listSubscribedWebhookEndpoints = `-- name: ListSubscribedWebhookEndpoints :many
SELECT id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
FROM webhook_endpoints
WHERE team_id = $1
  AND enabled = true
  AND disabled_at IS NULL
  AND $2::text = ANY(subscribed_events)
ORDER BY created_at, id
`

type ListSubscribedWebhookEndpointsParams struct {
	TeamID    uuid.UUID `db:"team_id" json:"team_id"`
	EventType string    `db:"event_type" json:"event_type"`
}

func (q *Queries) ListSubscribedWebhookEndpoints(ctx context.Context, arg ListSubscribedWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listSubscribedWebhookEndpoints, arg.TeamID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Url,
			&i.SigningSecret,
			&i.Enabled,
			&i.SubscribedEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
FROM webhook_endpoints
WHERE team_id = $1
ORDER BY created_at DESC
LIMIT $3
OFFSET $2
`

type ListWebhookEndpointsParams struct {
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
	OffsetCount int32     `db:"offset_count" json:"offset_count"`
	LimitCount  int32     `db:"limit_count" json:"limit_count"`
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.TeamID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Url,
			&i.SigningSecret,
			&i.Enabled,
			&i.SubscribedEvents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWebhookEndpointSecret = `-- name: RotateWebhookEndpointSecret :one
UPDATE webhook_endpoints
SET signing_secret = $1,
    updated_at = now()
WHERE id = $2
  AND team_id = $3
RETURNING id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
`

type RotateWebhookEndpointSecretParams struct {
	SigningSecret []byte    `db:"signing_secret" json:"signing_secret"`
	ID            uuid.UUID `db:"id" json:"id"`
	TeamID        uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RotateWebhookEndpointSecret(ctx context.Context, arg RotateWebhookEndpointSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookEndpointSecret, arg.SigningSecret, arg.ID, arg.TeamID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Url,
		&i.SigningSecret,
		&i.Enabled,
		&i.SubscribedEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url = $1,
    enabled = $2,
    subscribed_events = $3,
    disabled_at = CASE
        WHEN $2::boolean THEN NULL
        ELSE COALESCE(disabled_at, now())
    END,
    updated_at = now()
WHERE id = $4
  AND team_id = $5
RETURNING id, team_id, url, signing_secret, enabled, subscribed_events, created_at, updated_at, disabled_at
`

type UpdateWebhookEndpointParams struct {
	Url              string    `db:"url" json:"url"`
	Enabled          bool      `db:"enabled" json:"enabled"`
	SubscribedEvents []string  `db:"subscribed_events" json:"subscribed_events"`
	ID               uuid.UUID `db:"id" json:"id"`
	TeamID           uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.Url,
		arg.Enabled,
		arg.SubscribedEvents,
		arg.ID,
		arg.TeamID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Url,
		&i.SigningSecret,
		&i.Enabled,
		&i.SubscribedEvents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}
