// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workloads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkloadAccessToken = `-- name: CreateWorkloadAccessToken :one
INSERT INTO workload_access_tokens (workload_id, credential_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, workload_id, credential_id, token_hash, expires_at, last_used_at, revoked_at, created_at
`

type CreateWorkloadAccessTokenParams struct {
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	CredentialID uuid.UUID          `db:"credential_id" json:"credential_id"`
	TokenHash    string             `db:"token_hash" json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateWorkloadAccessToken(ctx context.Context, arg CreateWorkloadAccessTokenParams) (WorkloadAccessToken, error) {
	row := q.db.QueryRow(ctx, createWorkloadAccessToken,
		arg.WorkloadID,
		arg.CredentialID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i WorkloadAccessToken
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.CredentialID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkloadCredential = `-- name: CreateWorkloadCredential :one
INSERT INTO workload_credentials (workload_id, secret_hash, secret_prefix, expires_at)
SELECT wi.id, $1, $2, $3
FROM workload_identities wi
WHERE wi.id = $4 AND wi.team_id = $5 AND wi.status = 'active'
RETURNING id, workload_id, secret_hash, secret_prefix, expires_at, last_used_at, revoked_at, created_at
`

type CreateWorkloadCredentialParams struct {
	SecretHash   string             `db:"secret_hash" json:"secret_hash"`
	SecretPrefix string             `db:"secret_prefix" json:"secret_prefix"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateWorkloadCredential(ctx context.Context, arg CreateWorkloadCredentialParams) (WorkloadCredential, error) {
	row := q.db.QueryRow(ctx, createWorkloadCredential,
		arg.SecretHash,
		arg.SecretPrefix,
		arg.ExpiresAt,
		arg.WorkloadID,
		arg.TeamID,
	)
	var i WorkloadCredential
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.SecretHash,
		&i.SecretPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkloadIdentity = `-- name: CreateWorkloadIdentity :one
INSERT INTO workload_identities (team_id, name, description, permissions, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type CreateWorkloadIdentityParams struct {
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
	Name        string     `db:"name" json:"name"`
	Description string     `db:"description" json:"description"`
	Permissions []string   `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkloadIdentity(ctx context.Context, arg CreateWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, createWorkloadIdentity,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.CreatedBy,
	)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const disableWorkloadIdentity = `-- name: DisableWorkloadIdentity :one
UPDATE workload_identities
SET status = 'disabled', disabled_at = now(), updated_at = now()
WHERE id = $1 AND team_id = $2 AND status = 'active'
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type DisableWorkloadIdentityParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DisableWorkloadIdentity(ctx context.Context, arg DisableWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, disableWorkloadIdentity, arg.ID, arg.TeamID)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getActiveWorkloadAccessTokenByHash = `-- name: GetActiveWorkloadAccessTokenByHash :one
SELECT wat.id AS token_id, wat.credential_id, wi.id AS workload_id, wi.team_id, wi.name, wi.permissions, wat.expires_at
FROM workload_access_tokens wat
JOIN workload_identities wi ON wi.id = wat.workload_id
JOIN workload_credentials wc ON wc.id = wat.credential_id
JOIN teams t ON t.id = wi.team_id
WHERE wat.token_hash = $1
  AND wat.revoked_at IS NULL AND wat.expires_at > now()
  AND wc.revoked_at IS NULL AND wc.expires_at > now()
  AND wi.status = 'active' AND t.status = 'active'
`

type GetActiveWorkloadAccessTokenByHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

type GetActiveWorkloadAccessTokenByHashRow struct {
	TokenID      uuid.UUID          `db:"token_id" json:"token_id"`
	CredentialID uuid.UUID          `db:"credential_id" json:"credential_id"`
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
	Name         string             `db:"name" json:"name"`
	Permissions  []string           `db:"permissions" json:"permissions"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetActiveWorkloadAccessTokenByHash(ctx context.Context, arg GetActiveWorkloadAccessTokenByHashParams) (GetActiveWorkloadAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadAccessTokenByHash, arg.TokenHash)
	var i GetActiveWorkloadAccessTokenByHashRow
	err := row.Scan(
		&i.TokenID,
		&i.CredentialID,
		&i.WorkloadID,
		&i.TeamID,
		&i.Name,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveWorkloadCredentialByHash = `-- name: GetActiveWorkloadCredentialByHash :one
SELECT wc.id AS credential_id, wi.id AS workload_id, wi.team_id, wi.name, wi.permissions
FROM workload_credentials wc
JOIN workload_identities wi ON wi.id = wc.workload_id
JOIN teams t ON t.id = wi.team_id
WHERE wc.secret_hash = $1
  AND wc.revoked_at IS NULL AND wc.expires_at > now()
  AND wi.status = 'active' AND t.status = 'active'
`

type GetActiveWorkloadCredentialByHashParams struct {
	SecretHash string `db:"secret_hash" json:"secret_hash"`
}

type GetActiveWorkloadCredentialByHashRow struct {
	CredentialID uuid.UUID `db:"credential_id" json:"credential_id"`
	WorkloadID   uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	Name         string    `db:"name" json:"name"`
	Permissions  []string  `db:"permissions" json:"permissions"`
}

func (q *Queries) GetActiveWorkloadCredentialByHash(ctx context.Context, arg GetActiveWorkloadCredentialByHashParams) (GetActiveWorkloadCredentialByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadCredentialByHash, arg.SecretHash)
	var i GetActiveWorkloadCredentialByHashRow
	err := row.Scan(
		&i.CredentialID,
		&i.WorkloadID,
		&i.TeamID,
		&i.Name,
		&i.Permissions,
	)
	return i, err
}

const getWorkloadIdentity = `-- name: GetWorkloadIdentity :one
SELECT id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at FROM workload_identities
WHERE id = $1 AND team_id = $2
`

type GetWorkloadIdentityParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWorkloadIdentity(ctx context.Context, arg GetWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, getWorkloadIdentity, arg.ID, arg.TeamID)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listWorkloadIdentities = `-- name: ListWorkloadIdentities :many
SELECT id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at FROM workload_identities
WHERE team_id = $1
ORDER BY created_at DESC
`

type ListWorkloadIdentitiesParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListWorkloadIdentities(ctx context.Context, arg ListWorkloadIdentitiesParams) ([]WorkloadIdentity, error) {
	rows, err := q.db.Query(ctx, listWorkloadIdentities, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadIdentity{}
	for rows.Next() {
		var i WorkloadIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Permissions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkloadCredential = `-- name: RevokeWorkloadCredential :one
UPDATE workload_credentials wc
SET revoked_at = now()
FROM workload_identities wi
WHERE wc.id = $1 AND wc.workload_id = $2
  AND wc.workload_id = wi.id AND wi.team_id = $3 AND wc.revoked_at IS NULL
RETURNING wc.id, wc.workload_id, wc.secret_hash, wc.secret_prefix, wc.expires_at, wc.last_used_at, wc.revoked_at, wc.created_at
`

type RevokeWorkloadCredentialParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	WorkloadID uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RevokeWorkloadCredential(ctx context.Context, arg RevokeWorkloadCredentialParams) (WorkloadCredential, error) {
	row := q.db.QueryRow(ctx, revokeWorkloadCredential, arg.ID, arg.WorkloadID, arg.TeamID)
	var i WorkloadCredential
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.SecretHash,
		&i.SecretPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchWorkloadAccessToken = `-- name: TouchWorkloadAccessToken :exec
UPDATE workload_access_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

type TouchWorkloadAccessTokenParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchWorkloadAccessToken(ctx context.Context, arg TouchWorkloadAccessTokenParams) error {
	_, err := q.db.Exec(ctx, touchWorkloadAccessToken, arg.ID)
	return err
}

const touchWorkloadCredential = `-- name: TouchWorkloadCredential :exec
UPDATE workload_credentials SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

type TouchWorkloadCredentialParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchWorkloadCredential(ctx context.Context, arg TouchWorkloadCredentialParams) error {
	_, err := q.db.Exec(ctx, touchWorkloadCredential, arg.ID)
	return err
}

const updateWorkloadIdentity = `-- name: UpdateWorkloadIdentity :one
UPDATE workload_identities
SET name = $1, description = $2, permissions = $3, updated_at = now()
WHERE id = $4 AND team_id = $5 AND status = 'active'
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type UpdateWorkloadIdentityParams struct {
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Permissions []string  `db:"permissions" json:"permissions"`
	ID          uuid.UUID `db:"id" json:"id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateWorkloadIdentity(ctx context.Context, arg UpdateWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, updateWorkloadIdentity,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.ID,
		arg.TeamID,
	)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}
