// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workloads.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFederatedWorkloadAccessToken = `-- name: CreateFederatedWorkloadAccessToken :one
INSERT INTO workload_access_tokens(workload_id,federation_id,token_hash,expires_at) VALUES($1,$2,$3,$4) RETURNING id, workload_id, credential_id, token_hash, expires_at, last_used_at, revoked_at, created_at, federation_id
`

type CreateFederatedWorkloadAccessTokenParams struct {
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	FederationID *uuid.UUID         `db:"federation_id" json:"federation_id"`
	TokenHash    string             `db:"token_hash" json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateFederatedWorkloadAccessToken(ctx context.Context, arg CreateFederatedWorkloadAccessTokenParams) (WorkloadAccessToken, error) {
	row := q.db.QueryRow(ctx, createFederatedWorkloadAccessToken,
		arg.WorkloadID,
		arg.FederationID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i WorkloadAccessToken
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.CredentialID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FederationID,
	)
	return i, err
}

const createWorkloadAccessToken = `-- name: CreateWorkloadAccessToken :one
INSERT INTO workload_access_tokens (workload_id, credential_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, workload_id, credential_id, token_hash, expires_at, last_used_at, revoked_at, created_at, federation_id
`

type CreateWorkloadAccessTokenParams struct {
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	CredentialID *uuid.UUID         `db:"credential_id" json:"credential_id"`
	TokenHash    string             `db:"token_hash" json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateWorkloadAccessToken(ctx context.Context, arg CreateWorkloadAccessTokenParams) (WorkloadAccessToken, error) {
	row := q.db.QueryRow(ctx, createWorkloadAccessToken,
		arg.WorkloadID,
		arg.CredentialID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i WorkloadAccessToken
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.CredentialID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FederationID,
	)
	return i, err
}

const createWorkloadCredential = `-- name: CreateWorkloadCredential :one
INSERT INTO workload_credentials (workload_id, secret_hash, secret_prefix, expires_at)
SELECT wi.id, $1, $2, $3
FROM workload_identities wi
WHERE wi.id = $4 AND wi.team_id = $5 AND wi.status = 'active'
RETURNING id, workload_id, secret_hash, secret_prefix, expires_at, last_used_at, revoked_at, created_at
`

type CreateWorkloadCredentialParams struct {
	SecretHash   string             `db:"secret_hash" json:"secret_hash"`
	SecretPrefix string             `db:"secret_prefix" json:"secret_prefix"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateWorkloadCredential(ctx context.Context, arg CreateWorkloadCredentialParams) (WorkloadCredential, error) {
	row := q.db.QueryRow(ctx, createWorkloadCredential,
		arg.SecretHash,
		arg.SecretPrefix,
		arg.ExpiresAt,
		arg.WorkloadID,
		arg.TeamID,
	)
	var i WorkloadCredential
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.SecretHash,
		&i.SecretPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkloadIdentity = `-- name: CreateWorkloadIdentity :one
INSERT INTO workload_identities (team_id, name, description, permissions, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type CreateWorkloadIdentityParams struct {
	TeamID      uuid.UUID  `db:"team_id" json:"team_id"`
	Name        string     `db:"name" json:"name"`
	Description string     `db:"description" json:"description"`
	Permissions []string   `db:"permissions" json:"permissions"`
	CreatedBy   *uuid.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateWorkloadIdentity(ctx context.Context, arg CreateWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, createWorkloadIdentity,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.CreatedBy,
	)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const createWorkloadOIDCFederation = `-- name: CreateWorkloadOIDCFederation :one
INSERT INTO workload_oidc_federations(workload_id,name,issuer_url,audiences,subject,required_claims,enabled,created_by)
SELECT wi.id,$1,$2,$3,$4,$5,$6,$7
FROM workload_identities wi WHERE wi.id=$8 AND wi.team_id=$9 AND wi.status='active' RETURNING workload_oidc_federations.id, workload_oidc_federations.workload_id, workload_oidc_federations.name, workload_oidc_federations.issuer_url, workload_oidc_federations.audiences, workload_oidc_federations.subject, workload_oidc_federations.required_claims, workload_oidc_federations.enabled, workload_oidc_federations.created_by, workload_oidc_federations.created_at, workload_oidc_federations.updated_at
`

type CreateWorkloadOIDCFederationParams struct {
	Name           string     `db:"name" json:"name"`
	IssuerUrl      string     `db:"issuer_url" json:"issuer_url"`
	Audiences      []string   `db:"audiences" json:"audiences"`
	Subject        string     `db:"subject" json:"subject"`
	RequiredClaims []byte     `db:"required_claims" json:"required_claims"`
	Enabled        bool       `db:"enabled" json:"enabled"`
	CreatedBy      *uuid.UUID `db:"created_by" json:"created_by"`
	WorkloadID     uuid.UUID  `db:"workload_id" json:"workload_id"`
	TeamID         uuid.UUID  `db:"team_id" json:"team_id"`
}

func (q *Queries) CreateWorkloadOIDCFederation(ctx context.Context, arg CreateWorkloadOIDCFederationParams) (WorkloadOidcFederation, error) {
	row := q.db.QueryRow(ctx, createWorkloadOIDCFederation,
		arg.Name,
		arg.IssuerUrl,
		arg.Audiences,
		arg.Subject,
		arg.RequiredClaims,
		arg.Enabled,
		arg.CreatedBy,
		arg.WorkloadID,
		arg.TeamID,
	)
	var i WorkloadOidcFederation
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.Name,
		&i.IssuerUrl,
		&i.Audiences,
		&i.Subject,
		&i.RequiredClaims,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkloadOIDCFederation = `-- name: DeleteWorkloadOIDCFederation :exec
DELETE FROM workload_oidc_federations f USING workload_identities wi WHERE f.id=$1 AND f.workload_id=$2 AND wi.id=f.workload_id AND wi.team_id=$3
`

type DeleteWorkloadOIDCFederationParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	WorkloadID uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DeleteWorkloadOIDCFederation(ctx context.Context, arg DeleteWorkloadOIDCFederationParams) error {
	_, err := q.db.Exec(ctx, deleteWorkloadOIDCFederation, arg.ID, arg.WorkloadID, arg.TeamID)
	return err
}

const disableWorkloadIdentity = `-- name: DisableWorkloadIdentity :one
UPDATE workload_identities
SET status = 'disabled', disabled_at = now(), updated_at = now()
WHERE id = $1 AND team_id = $2 AND status = 'active'
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type DisableWorkloadIdentityParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) DisableWorkloadIdentity(ctx context.Context, arg DisableWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, disableWorkloadIdentity, arg.ID, arg.TeamID)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getActiveWorkloadAccessTokenByHash = `-- name: GetActiveWorkloadAccessTokenByHash :one
SELECT wat.id AS token_id, wat.credential_id, wi.id AS workload_id, wi.team_id, wi.name, wi.permissions, wat.expires_at
FROM workload_access_tokens wat
JOIN workload_identities wi ON wi.id = wat.workload_id
LEFT JOIN workload_credentials wc ON wc.id = wat.credential_id
LEFT JOIN workload_oidc_federations wof ON wof.id = wat.federation_id
JOIN teams t ON t.id = wi.team_id
WHERE wat.token_hash = $1
  AND wat.revoked_at IS NULL AND wat.expires_at > now()
  AND ((wat.credential_id IS NOT NULL AND wc.revoked_at IS NULL AND wc.expires_at > now())
    OR (wat.federation_id IS NOT NULL AND wof.enabled))
  AND wi.status = 'active' AND t.status = 'active'
`

type GetActiveWorkloadAccessTokenByHashParams struct {
	TokenHash string `db:"token_hash" json:"token_hash"`
}

type GetActiveWorkloadAccessTokenByHashRow struct {
	TokenID      uuid.UUID          `db:"token_id" json:"token_id"`
	CredentialID *uuid.UUID         `db:"credential_id" json:"credential_id"`
	WorkloadID   uuid.UUID          `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID          `db:"team_id" json:"team_id"`
	Name         string             `db:"name" json:"name"`
	Permissions  []string           `db:"permissions" json:"permissions"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetActiveWorkloadAccessTokenByHash(ctx context.Context, arg GetActiveWorkloadAccessTokenByHashParams) (GetActiveWorkloadAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadAccessTokenByHash, arg.TokenHash)
	var i GetActiveWorkloadAccessTokenByHashRow
	err := row.Scan(
		&i.TokenID,
		&i.CredentialID,
		&i.WorkloadID,
		&i.TeamID,
		&i.Name,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveWorkloadCredentialByHash = `-- name: GetActiveWorkloadCredentialByHash :one
SELECT wc.id AS credential_id, wi.id AS workload_id, wi.team_id, wi.name, wi.permissions
FROM workload_credentials wc
JOIN workload_identities wi ON wi.id = wc.workload_id
JOIN teams t ON t.id = wi.team_id
WHERE wc.secret_hash = $1
  AND wc.revoked_at IS NULL AND wc.expires_at > now()
  AND wi.status = 'active' AND t.status = 'active'
`

type GetActiveWorkloadCredentialByHashParams struct {
	SecretHash string `db:"secret_hash" json:"secret_hash"`
}

type GetActiveWorkloadCredentialByHashRow struct {
	CredentialID uuid.UUID `db:"credential_id" json:"credential_id"`
	WorkloadID   uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID       uuid.UUID `db:"team_id" json:"team_id"`
	Name         string    `db:"name" json:"name"`
	Permissions  []string  `db:"permissions" json:"permissions"`
}

func (q *Queries) GetActiveWorkloadCredentialByHash(ctx context.Context, arg GetActiveWorkloadCredentialByHashParams) (GetActiveWorkloadCredentialByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadCredentialByHash, arg.SecretHash)
	var i GetActiveWorkloadCredentialByHashRow
	err := row.Scan(
		&i.CredentialID,
		&i.WorkloadID,
		&i.TeamID,
		&i.Name,
		&i.Permissions,
	)
	return i, err
}

const getActiveWorkloadOIDCFederation = `-- name: GetActiveWorkloadOIDCFederation :one
SELECT f.id, f.workload_id, f.name, f.issuer_url, f.audiences, f.subject, f.required_claims, f.enabled, f.created_by, f.created_at, f.updated_at,wi.team_id,wi.name AS workload_name,wi.permissions FROM workload_oidc_federations f JOIN workload_identities wi ON wi.id=f.workload_id JOIN teams t ON t.id=wi.team_id WHERE f.id=$1 AND f.enabled AND wi.status='active' AND t.status='active'
`

type GetActiveWorkloadOIDCFederationParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

type GetActiveWorkloadOIDCFederationRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	WorkloadID     uuid.UUID          `db:"workload_id" json:"workload_id"`
	Name           string             `db:"name" json:"name"`
	IssuerUrl      string             `db:"issuer_url" json:"issuer_url"`
	Audiences      []string           `db:"audiences" json:"audiences"`
	Subject        string             `db:"subject" json:"subject"`
	RequiredClaims []byte             `db:"required_claims" json:"required_claims"`
	Enabled        bool               `db:"enabled" json:"enabled"`
	CreatedBy      *uuid.UUID         `db:"created_by" json:"created_by"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TeamID         uuid.UUID          `db:"team_id" json:"team_id"`
	WorkloadName   string             `db:"workload_name" json:"workload_name"`
	Permissions    []string           `db:"permissions" json:"permissions"`
}

func (q *Queries) GetActiveWorkloadOIDCFederation(ctx context.Context, arg GetActiveWorkloadOIDCFederationParams) (GetActiveWorkloadOIDCFederationRow, error) {
	row := q.db.QueryRow(ctx, getActiveWorkloadOIDCFederation, arg.ID)
	var i GetActiveWorkloadOIDCFederationRow
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.Name,
		&i.IssuerUrl,
		&i.Audiences,
		&i.Subject,
		&i.RequiredClaims,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
		&i.WorkloadName,
		&i.Permissions,
	)
	return i, err
}

const getWorkloadIdentity = `-- name: GetWorkloadIdentity :one
SELECT id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at FROM workload_identities
WHERE id = $1 AND team_id = $2
`

type GetWorkloadIdentityParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) GetWorkloadIdentity(ctx context.Context, arg GetWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, getWorkloadIdentity, arg.ID, arg.TeamID)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listWorkloadIdentities = `-- name: ListWorkloadIdentities :many
SELECT id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at FROM workload_identities
WHERE team_id = $1
ORDER BY created_at DESC
`

type ListWorkloadIdentitiesParams struct {
	TeamID uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListWorkloadIdentities(ctx context.Context, arg ListWorkloadIdentitiesParams) ([]WorkloadIdentity, error) {
	rows, err := q.db.Query(ctx, listWorkloadIdentities, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadIdentity{}
	for rows.Next() {
		var i WorkloadIdentity
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Permissions,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkloadOIDCFederations = `-- name: ListWorkloadOIDCFederations :many
SELECT f.id, f.workload_id, f.name, f.issuer_url, f.audiences, f.subject, f.required_claims, f.enabled, f.created_by, f.created_at, f.updated_at FROM workload_oidc_federations f JOIN workload_identities wi ON wi.id=f.workload_id WHERE f.workload_id=$1 AND wi.team_id=$2 ORDER BY f.created_at
`

type ListWorkloadOIDCFederationsParams struct {
	WorkloadID uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) ListWorkloadOIDCFederations(ctx context.Context, arg ListWorkloadOIDCFederationsParams) ([]WorkloadOidcFederation, error) {
	rows, err := q.db.Query(ctx, listWorkloadOIDCFederations, arg.WorkloadID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkloadOidcFederation{}
	for rows.Next() {
		var i WorkloadOidcFederation
		if err := rows.Scan(
			&i.ID,
			&i.WorkloadID,
			&i.Name,
			&i.IssuerUrl,
			&i.Audiences,
			&i.Subject,
			&i.RequiredClaims,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkloadCredential = `-- name: RevokeWorkloadCredential :one
UPDATE workload_credentials wc
SET revoked_at = now()
FROM workload_identities wi
WHERE wc.id = $1 AND wc.workload_id = $2
  AND wc.workload_id = wi.id AND wi.team_id = $3 AND wc.revoked_at IS NULL
RETURNING wc.id, wc.workload_id, wc.secret_hash, wc.secret_prefix, wc.expires_at, wc.last_used_at, wc.revoked_at, wc.created_at
`

type RevokeWorkloadCredentialParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	WorkloadID uuid.UUID `db:"workload_id" json:"workload_id"`
	TeamID     uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) RevokeWorkloadCredential(ctx context.Context, arg RevokeWorkloadCredentialParams) (WorkloadCredential, error) {
	row := q.db.QueryRow(ctx, revokeWorkloadCredential, arg.ID, arg.WorkloadID, arg.TeamID)
	var i WorkloadCredential
	err := row.Scan(
		&i.ID,
		&i.WorkloadID,
		&i.SecretHash,
		&i.SecretPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchWorkloadAccessToken = `-- name: TouchWorkloadAccessToken :exec
UPDATE workload_access_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

type TouchWorkloadAccessTokenParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchWorkloadAccessToken(ctx context.Context, arg TouchWorkloadAccessTokenParams) error {
	_, err := q.db.Exec(ctx, touchWorkloadAccessToken, arg.ID)
	return err
}

const touchWorkloadCredential = `-- name: TouchWorkloadCredential :exec
UPDATE workload_credentials SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

type TouchWorkloadCredentialParams struct {
	ID uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) TouchWorkloadCredential(ctx context.Context, arg TouchWorkloadCredentialParams) error {
	_, err := q.db.Exec(ctx, touchWorkloadCredential, arg.ID)
	return err
}

const updateWorkloadIdentity = `-- name: UpdateWorkloadIdentity :one
UPDATE workload_identities
SET name = $1, description = $2, permissions = $3, updated_at = now()
WHERE id = $4 AND team_id = $5 AND status = 'active'
RETURNING id, team_id, name, description, status, permissions, created_by, created_at, updated_at, disabled_at
`

type UpdateWorkloadIdentityParams struct {
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Permissions []string  `db:"permissions" json:"permissions"`
	ID          uuid.UUID `db:"id" json:"id"`
	TeamID      uuid.UUID `db:"team_id" json:"team_id"`
}

func (q *Queries) UpdateWorkloadIdentity(ctx context.Context, arg UpdateWorkloadIdentityParams) (WorkloadIdentity, error) {
	row := q.db.QueryRow(ctx, updateWorkloadIdentity,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.ID,
		arg.TeamID,
	)
	var i WorkloadIdentity
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Permissions,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
	)
	return i, err
}
